[FEAT] 소소피드 전체 조회 API 구현
Team-WSS/WSS-Server pull request #100
Opened 2024-07-15 14:37 UTC by ChaeAg

## Related Issue

- feat/#77 -> dev
- close #77 

## Key Changes

### 소소피드 전체를 조회하는 API를 구현했습니다. (무한스크롤)

## To Reviewers

엔티티 수정사항 반영 건에 비하면 비교적 간단(?) 합니다 허허허 ..

## References

2024-07-15 14:43 UTC, ChaeAg commented on src/main/java/org/websoso/WSSServer/dto/feed/FeedInfo.java
> +        }
해당 Feed 와 연결된 novel 이 있는 경우를 위한 로직

2024-07-15 14:43 UTC, ChaeAg commented on src/main/java/org/websoso/WSSServer/repository/FeedCategoryRepository.java
> +    Slice<Feed> findFeedByCategory(Category category, Long lastFeedId, PageRequest pageRequest);
파라미터의 category와 일치하면서, 숨겨진 피드(isHidden이 true)를 제외하고 정해진 크기만큼 조회하는 쿼리

2024-07-15 14:43 UTC, ChaeAg commented on src/main/java/org/websoso/WSSServer/service/FeedService.java
> +    }
카테고리로 해당하는 Feed를 찾는 메서드

2024-07-15 14:43 UTC, ChaeAg commented on src/main/java/org/websoso/WSSServer/service/FeedService.java
> +        }
반복문 존재 이유 : 피드 작성자와 보고있는 유저가 서로 차단상태이면 그 피드는 제외하고 Response에 담아야 하기 때문에,
만약 size가 3일때 **1개가 차단유저피드**라면 2개만 Response에 담기게 되는 식. 
-> 반복문을 통해 원하는 size만큼 담도록 함.

2024-07-16 06:17 UTC, rinarina0429 requested changes
수고하셨습니다아!! 뭐 큰건 없고.. 작은 코멘트 하나 남기구 갑니다아

2024-07-16 06:17 UTC, rinarina0429 commented on src/main/java/org/websoso/WSSServer/repository/FeedCategoryRepository.java
> +    Slice<Feed> findFeedByCategory(Category category, Long lastFeedId, PageRequest pageRequest);
p3; FeedRepository와 같이 findFeed**s**ByCategory로 변경하는건 어떠신가요?

2024-07-17 02:00 UTC, ChaeAg commented on src/main/java/org/websoso/WSSServer/repository/FeedCategoryRepository.java
> +    Slice<Feed> findFeedByCategory(Category category, Long lastFeedId, PageRequest pageRequest);
아핳 좋습니다!! 수정했어요!

2024-07-17 03:37 UTC, rinarina0429 approved these changes
수고하셨습니다~~

2024-07-26 06:48 UTC, Kim-TaeUk commented on src/main/java/org/websoso/WSSServer/dto/feed/FeedInfo.java
> +        Float novelRating = null;
p3;
Wrapper 타입이라서 디폴트가 null인데 명시적으로 null로 세팅하는 이유가 있나욥?

2024-07-26 06:50 UTC, Kim-TaeUk commented on src/main/java/org/websoso/WSSServer/controller/FeedController.java
> +        User user = principal == null ? null : userService.getUserOrException(Long.valueOf(principal.getName()));
p5;
개행 추가 하는거 어떠신가요? 
삼항 연산자 쓸 때 어떻게 쓰면 가독성이 좋을까 찾아보다가 하나 남깁니다!
https://medium.com/hayanmind-tech-blog-kr/3항-연산자의-재발견-a3f815bcdbb8

2024-07-26 06:50 UTC, Kim-TaeUk commented on src/main/java/org/websoso/WSSServer/domain/common/CategoryName.java
> +    etc("기타");
q;
한글로 바뀐 이유가 있나요?

2024-07-29 06:04 UTC, ChaeAg commented on src/main/java/org/websoso/WSSServer/domain/common/CategoryName.java
> +    etc("기타");
원래는 소문자 영어로 된 이름들을 라벨로 사용했는데 해당 이름을 DB에 넣게 되어서 상수명을 소문자영어로 하고 나중에 조회할 경우에 사용하기 위해 한글을 매칭해주었습니다!

2024-07-29 06:06 UTC, ChaeAg commented on src/main/java/org/websoso/WSSServer/controller/FeedController.java
> +        User user = principal == null ? null : userService.getUserOrException(Long.valueOf(principal.getName()));
오 좋은 것 같은걸요!!
요 부분은 나중에 ~ 개발을 다 마치고 리팩토링할 때 한번에 다 변경해보겠습니다!!
제가 은근 삼항을 많이 써가지구요 ..ㅎㅎ

2024-07-29 06:11 UTC, ChaeAg commented on src/main/java/org/websoso/WSSServer/dto/feed/FeedInfo.java
> +        Float novelRating = null;
저두 의문인데 왜인지 모르겠지만 null로 초기화를 시켜주지 않으면
Variable 'title' might not have been initialized
이런 메세지가 나오면서 컴파일 오류가 나게 되더라구요.

2024-07-29 17:43 UTC, Kim-TaeUk commented on src/main/java/org/websoso/WSSServer/dto/feed/FeedInfo.java
> +        Float novelRating = null;
아 다시 생각해보니까 지역 변수라서 무조건 초기화해줘야하겠네요 ㅋㅋ..

2024-07-29 17:47 UTC, Kim-TaeUk commented on src/main/java/org/websoso/WSSServer/repository/FeedCategoryRepository.java
> +    Slice<Feed> findFeedsByCategory(Category category, Long lastFeedId, Long userId, PageRequest pageRequest);
q2;
JPQL 사용 시, 파라미터 바인딩 할 때 가급적 위치보다는 이름 기준으로 하는 것이 좋아 보입니다.
파라미터의 시그니처가 변하면 장애로 이어질 수도 있어서요!

2024-07-29 17:53 UTC, Kim-TaeUk commented on src/main/java/org/websoso/WSSServer/repository/FeedCategoryRepository.java
>      Optional<List<FeedCategory>> findByFeed(Feed feed);
p2;
지금 PR에서 개발한 내용이 아니긴 한데, List를 Optional로 wrapping하는 것이 불필요하고, 안티 패턴인데 발견하게 돼서 코멘트 남깁니다...!

`ref`: https://mangkyu.tistory.com/203

2024-07-29 17:53 UTC, Kim-TaeUk commented on src/main/java/org/websoso/WSSServer/repository/FeedRepository.java
> +    Slice<Feed> findFeeds(Long lastFeedId, Long userId, PageRequest pageRequest);
q2;
JPQL 사용 시, 파라미터 바인딩 할 때 가급적 위치보다는 이름 기준으로 하는 것이 좋아 보입니다.
파라미터의 시그니처가 변하면 장애로 이어질 수도 있어서요!

2024-07-29 18:00 UTC, Kim-TaeUk commented on src/main/java/org/websoso/WSSServer/dto/feed/FeedInfo.java
> +            List<UserNovel> userNovels = novel.getUserNovels().stream().filter(un -> un.getUserNovelRating() > 0.0)
p3;
stream api 사용 할 때 가독성을 위해 개행하면 좋을 것 같아요!
레퍼런스를 찾아보려고 했는데 못찾았지만 `.` 단위로 개행하면 좋다고 합니다!

2024-07-29 18:02 UTC, Kim-TaeUk commented on src/main/java/org/websoso/WSSServer/dto/feed/FeedInfo.java
> +            List<UserNovel> userNovels = novel.getUserNovels().stream().filter(un -> un.getUserNovelRating() > 0.0)
저도 볼 때마다, 쓸 때마다 기준 없이 썼는데, 
지금부터라도 저희 팀 컨벤션으로 설정해도 괜찮을 것 같아요

2024-07-29 18:03 UTC, Kim-TaeUk commented on src/main/java/org/websoso/WSSServer/dto/feed/FeedInfo.java
> +                    (float) userNovels.stream().map(UserNovel::getUserNovelRating).mapToDouble(d -> d).sum(),
p3;
여기도 개행 있으면 좋을것 같아요~

2024-07-29 18:07 UTC, Kim-TaeUk commented on src/main/java/org/websoso/WSSServer/domain/common/CategoryName.java
> +    etc("기타");
소문자 영어로 된 이름들(ex. romanceFantasy)을 label로 사용했는데, 해당 이름을 DB에 넣게 된 것이랑

상수명을 소문자 영어로(ex. romanceFantasy) 설정하고, 나중에 조회할 경우에 사용하기 위해 한글(ex. 로판)로 매칭한 것이 무슨 연관이 있는지 잘 이해가 가지 않습니다.

DB에 소문자 영어로 들어가니까 기존대로 써야 categoryName으로 쿼리 날릴 때도 편하지 않을까 생각이 들어서요. 잘못 생각하고 있는 것일 수도 있어서, 좀 더 자세히 설명해주실 수 있을까요?

2024-07-29 18:07 UTC, Kim-TaeUk commented on src/main/java/org/websoso/WSSServer/dto/feed/FeedInfo.java
> +            List<UserNovel> userNovels = novel.getUserNovels().stream().filter(un -> un.getUserNovelRating() > 0.0)
@rinarina0429 @ChaeAg

2024-07-29 19:07 UTC, Kim-TaeUk requested changes
코멘트 남겨두었습니다!

2024-07-30 01:30 UTC, ChaeAg commented on src/main/java/org/websoso/WSSServer/domain/common/CategoryName.java
> +    etc("기타");
1. 먼저, `Category` 엔티티 내의 `categoryName` 컬럼의 타입이 해당 `CategoryName` **Enum 클래스** 입니다<img width="479" alt="image" src="https://github.com/user-attachments/assets/c2ade848-518d-4d8e-bb86-6dbe0f59b760">
그래서 EnumType.STRING 을 사용해 DB 테이블과 매칭 시켜주게 되면 해당 Enum 클래스의 상수명으로 값이 매칭되기 때문에 수정한 것입니다!
만약 기존대로 한다면 -> Category 테이블 category_name 컬럼에 RO, RF 와 같은 값이 들어가게 됩니다!

2. 한글 이름을 라벨로 작성한 것은, 조회 결과 DTO 에 카테고리 이름(영어) 값을 한글 이름으로 변환할 때 사용하기 위함이었습니다!

2024-07-30 01:53 UTC, ChaeAg commented on src/main/java/org/websoso/WSSServer/dto/feed/FeedInfo.java
> +            List<UserNovel> userNovels = novel.getUserNovels().stream().filter(un -> un.getUserNovelRating() > 0.0)
좋습니다! 저도 맨날 다르게 썼었는데 개행하는 것 찬성이에요!
정해진 뒤에 한번에 리팩토링 하면 어떨까요 ..! 삼항 연산자 컨벤션도 그렇고 널리 많이 퍼져있는 것 같아서요 ...!!

2024-07-30 01:53 UTC, ChaeAg commented on src/main/java/org/websoso/WSSServer/repository/FeedCategoryRepository.java
>      Optional<List<FeedCategory>> findByFeed(Feed feed);
헉 감사합니다!!! 아무 생각없이 사용했었나보네요 불필요한 Optional은 제거했습니다!

2024-07-30 01:53 UTC, ChaeAg commented on src/main/java/org/websoso/WSSServer/repository/FeedCategoryRepository.java
> +    Slice<Feed> findFeedsByCategory(Category category, Long lastFeedId, Long userId, PageRequest pageRequest);
감사합니다! 수정완료 했습니다 👍

2024-07-30 01:53 UTC, ChaeAg commented on src/main/java/org/websoso/WSSServer/repository/FeedRepository.java
> +    Slice<Feed> findFeeds(Long lastFeedId, Long userId, PageRequest pageRequest);
감사합니다! 수정완료 했습니다 👍

2024-07-30 14:01 UTC, rinarina0429 commented on src/main/java/org/websoso/WSSServer/dto/feed/FeedInfo.java
> +            List<UserNovel> userNovels = novel.getUserNovels().stream().filter(un -> un.getUserNovelRating() > 0.0)
좋습니다!! 개발하면서 중간중간 도입한 컨벤션들이 있어 마지막에 한번 리팩토링 하는 것도 필요할 것 같습니다!!

2024-07-31 00:58 UTC, Kim-TaeUk commented on src/main/java/org/websoso/WSSServer/domain/common/CategoryName.java
> +    etc("기타");
아하!!! 이해 완입니다 ^_^
감사합니닷

2024-07-31 01:01 UTC, Kim-TaeUk commented on src/main/java/org/websoso/WSSServer/repository/FeedCategoryRepository.java
>      Optional<List<FeedCategory>> findByFeed(Feed feed);
로직도 더 깔끔해진 것 같네요! 👍

2024-07-31 01:02 UTC, Kim-TaeUk commented on src/main/java/org/websoso/WSSServer/dto/feed/FeedInfo.java
> +            List<UserNovel> userNovels = novel.getUserNovels().stream().filter(un -> un.getUserNovelRating() > 0.0)
넵 그러면 일단 앞으로 열리는 PR에서는 stream하고 삼항 연산자 사용할 때 개행 신경쓰는 것으로 하고,
컨벤션대로 수정은 일괄적으로 하는 것으로 합시닷!

2024-07-31 01:03 UTC, Kim-TaeUk approved these changes
리뷰 내용도 모두 반영된 것 같네요.
고생하셨습니다!
머지 레지고

2024-07-31 03:26 UTC, merged