[FEAT] 관심있어요 삭제 API 구현
Team-WSS/WSS-Server pull request #102
Opened 2024-07-16 03:30 UTC by rinarina0429

## Related Issue

- feat/#101 -> dev
- close #101 

## Key Changes

관심 등록을 삭제하는 API를 구현했습니다.
- 만약 관심 등록만으로 서재에 등록되었던 작품이라면 userNovel에서도 삭제합니다.

## To Reviewers

## References

2024-07-16 03:32 UTC, rinarina0429 commented on src/main/java/org/websoso/WSSServer/controller/NovelController.java
>      }
✅

2024-07-16 03:33 UTC, rinarina0429 commented on src/main/java/org/websoso/WSSServer/exception/error/CustomUserNovelError.java
✅

2024-07-16 03:34 UTC, rinarina0429 commented on src/main/java/org/websoso/WSSServer/service/NovelService.java
> +    public void unregisterAsInterest(User user, Long novelId) {
✅

2024-07-17 07:02 UTC, ChaeAg approved these changes
굿! 수고하셨서용 :>

2024-07-19 06:25 UTC, Kim-TaeUk commented on src/main/java/org/websoso/WSSServer/exception/error/CustomUserNovelError.java
> +    NOT_INTERESTED("USER_NOVEL-004", "관심으로 등록되어 있지 않은 작품입니다.", CONFLICT);
p2;
400이 낫지 않을까욥!?

2024-07-19 06:43 UTC, Kim-TaeUk commented on src/main/java/org/websoso/WSSServer/service/NovelService.java
> +        UserNovel userNovel = userNovelService.getUserNovelOrNull(user, novel);
q;
userNovelRepository에서 user랑 novel로 찾고 없으면 바로 익셉션을 던져도 될 것 같은데,
null로 설정해두고 아래 조건문에서 판단하는 이유가 있나요!?

2024-07-19 06:45 UTC, Kim-TaeUk requested changes
코멘트 남겨놓았습니다~ 확인하고 리리뷰 주셔요~~

2024-07-20 16:14 UTC, rinarina0429 commented on src/main/java/org/websoso/WSSServer/exception/error/CustomUserNovelError.java
> +    NOT_INTERESTED("USER_NOVEL-004", "관심으로 등록되어 있지 않은 작품입니다.", CONFLICT);
맞습니다!! BAD_REQUEST로 수정하였습니다~

2024-07-21 11:37 UTC, rinarina0429 commented on src/main/java/org/websoso/WSSServer/service/NovelService.java
> +        UserNovel userNovel = userNovelService.getUserNovelOrNull(user, novel);
getUserNovelOrNull 대신 getUserNovelOrException 사용하도록 수정했습니다!

2024-07-21 11:43 UTC, Kim-TaeUk approved these changes
고생하셨습네다! 👍

2024-07-21 11:45 UTC, merged