[FEAT] 작품평가 삭제 API 구현
Team-WSS/WSS-Server pull request #106
Opened 2024-07-16 11:48 UTC by rinarina0429

## Related Issue

- feat/#85 -> dev
- close #85 

## Key Changes

작품평가를 삭제하는 API를 구현했습니다.
- 평가를 삭제한다고 userNovel을 모두 삭제해버리는 것이 아니라,
  - 관심으로 등록되어 있으면 startDate, endDate, status, userNovelRating을 초기화
  - 관심으로 등록되어 있지 않다면 userNovel 삭제를 진행합니다. (동시에 해당 NovelKeyword와 UserNovelAttractivePoint도 삭제)

## To Reviewers

## References

2024-07-17 07:11 UTC, ChaeAg requested changes
수고하셨어용 코멘트남겼슴다!

2024-07-17 07:11 UTC, ChaeAg commented on src/main/java/org/websoso/WSSServer/service/UserNovelService.java
> +        userNovelAttractivePointRepository.deleteAll(userNovelAttractivePoints);
P4; 혹시 해당 과정을 `UserNovel` 엔티티 내에 @OneToMany로 매력포인트랑 관계를 맺어서 
```java
userNovelAttractivePointRepository.deleteAll(userNovel.getUserNovelAttractivePoints());
```
와 같이 가져오는 것은 어떨까요?
`UserNovelAttractivePoint` 는 `UserNovel`의 **완전한 개인소유** 라고 저는 생각해서 매핑 하고 cascade 옵션을 걸어줘도 좋을 것 같아서용!

2024-07-18 04:05 UTC, rinarina0429 commented on src/main/java/org/websoso/WSSServer/service/UserNovelService.java
> +        userNovelAttractivePointRepository.deleteAll(userNovelAttractivePoints);
너무 좋슴니다! 해당 방식대로 수정했습니다~~

2024-07-19 01:37 UTC, ChaeAg approved these changes
굿! 수고많으셨어용 😊 🙌

2024-07-19 08:10 UTC, Kim-TaeUk commented on src/main/java/org/websoso/WSSServer/domain/UserNovel.java
> +@DynamicUpdate
q;
`@DynamicUpdate`를 사용한 이유가 무엇일까요?

2024-07-19 08:12 UTC, Kim-TaeUk commented on src/main/java/org/websoso/WSSServer/exception/error/CustomUserNovelError.java
> +    NOT_EVALUATED("USER_NOVEL-005", "평가하지 않은 작품입니다.", CONFLICT);
p2;
400이 낫지 않을까요? 409는 보통 타깃 리소스랑 충돌이 발생할 때 사용하는데, 
평가하지 않은 작품인 경우 리소스 자체가 없는거니까 충돌이랑은 거리가 좀 먼 것 같아요!

`ref`: https://developer.mozilla.org/ko/docs/Web/HTTP/Status/409

2024-07-19 08:44 UTC, Kim-TaeUk commented on src/main/java/org/websoso/WSSServer/service/UserNovelService.java
> +        UserNovel userNovel = getUserNovelOrNull(user, novel);
p3;
여기서 null로 할당해두고 아래에서 null일 때 예외를 터뜨리는 이유가 뭘까요!?
찾아서 없으면 바로 예외를 던져도 되지 않나요?

2024-07-19 09:09 UTC, Kim-TaeUk commented on src/main/java/org/websoso/WSSServer/domain/UserNovel.java
> +    @OneToMany(mappedBy = "userNovel", cascade = ALL, fetch = FetchType.LAZY)
p2;
부모 엔티티로 자식 엔티티 생명주기를 관리하려고 한다면 orphanRemoval도 걸어주면 어떨까욥?
```suggestion
    @OneToMany(mappedBy = "userNovel", cascade = ALL, fetch = FetchType.LAZY, orphanRemoval = true)
```

2024-07-19 09:10 UTC, Kim-TaeUk commented on src/main/java/org/websoso/WSSServer/domain/UserNovel.java
> +
p2;
부모 엔티티로 자식 엔티티 생명주기를 관리하려고 한다면 orphanRemoval도 걸어주면 어떨까욥?
```suggestion
    @OneToMany(mappedBy = "userNovel", cascade = ALL, fetch = FetchType.LAZY, orphanRemoval = true)
```

2024-07-19 15:17 UTC, Kim-TaeUk commented on src/main/java/org/websoso/WSSServer/repository/UserNovelKeywordRepository.java
> +    List<UserNovelKeyword> findAllByUserNovel_Novel(Novel novel);
q;
오 쿼리메서드에서 언더스코어를 사용해서 모호성을 해결하네요!! 처음 보는데 신기합니닷 (https://docs.spring.io/spring-data/jpa/reference/repositories/query-methods-details.html#repositories.query-methods.query-property-expressions)

UserNovel에 Novel로 경로를 지정하고 싶어서 사용한걸까요?

2024-07-19 15:17 UTC, Kim-TaeUk requested changes
코멘트 남겨두었습니다~

2024-07-20 15:52 UTC, rinarina0429 commented on src/main/java/org/websoso/WSSServer/domain/UserNovel.java
> +@DynamicUpdate
중간에 수정하다가 들어간건데, 안뺐네요! 필요 없어 일단 제거하겠습니다

2024-07-20 15:54 UTC, rinarina0429 commented on src/main/java/org/websoso/WSSServer/service/UserNovelService.java
> +        UserNovel userNovel = getUserNovelOrNull(user, novel);
아무 생각 없이 기존에 있던 함수를 사용하는 과정에서 이런 코드가 나와버렸네요.. 찾아주셔서 감사합니다 수정하겠습니다!

2024-07-20 16:02 UTC, rinarina0429 commented on src/main/java/org/websoso/WSSServer/domain/UserNovel.java
> +
너무너무 좋은 생각입니다! 저번에 얘기가 나왔던 것 같은데 제가 잊었네요😅 추가하겠습니다~!

2024-07-20 16:04 UTC, rinarina0429 commented on src/main/java/org/websoso/WSSServer/repository/UserNovelKeywordRepository.java
> +    List<UserNovelKeyword> findAllByUserNovel_Novel(Novel novel);
네! 맞습니다 UserNovelKeyword는 UserNovel과 Keyword만 가지고 있는데 Novel로 가져와야 하는 상황이 있어 해당 방식을 사용했숨니다

2024-07-20 16:08 UTC, rinarina0429 commented on src/main/java/org/websoso/WSSServer/exception/error/CustomUserNovelError.java
> +    NOT_EVALUATED("USER_NOVEL-005", "평가하지 않은 작품입니다.", CONFLICT);
매우 그렇네요. 400이 해당 상황에 가장 적절한 것 같아 400으로 수정하도록 하겠습니다~

2024-07-21 08:10 UTC, Kim-TaeUk approved these changes
반영이 모두 잘 되었네요! 고생하셨습니다.
어푸룹하겠습니다.

2024-07-21 11:16 UTC, merged