[FEAT] 작품평가 수정 API 구현
Team-WSS/WSS-Server pull request #107
Opened 2024-07-17 04:29 UTC by rinarina0429

## Related Issue

- feat/#84 -> dev
- close #84 

## Key Changes

작품평가를 수정하는 API를 구현했습니다.
- 작품평가 조회, 생성, 수정의 함수명이 기존에는 deleteUserNovel(), updateUserNovel()과 같은 방식이었는데 작품평가 삭제의 경우, 관심으로 등록이 되어있으면 평가만 초기화될 뿐 UserNovel이 삭제되는게 아니라 어색하다고 느껴서 deleteEvaluation(), updateEvaluation() 등으로 수정했습니다.

## To Reviewers

## References

2024-07-17 04:30 UTC, rinarina0429 commented on src/main/java/org/websoso/WSSServer/exception/error/CustomUserNovelError.java
> +    NOT_EVALUATED("USER_NOVEL-005", "평가하지 않은 작품입니다.", CONFLICT);
이미 올라와있는 다른 pr에서 USER_NOVEL-004가 있어 바로 005가 되었습니다.

2024-07-17 07:18 UTC, ChaeAg approved these changes
수고많으셨습니당 !! ><

2024-07-17 07:18 UTC, ChaeAg commented on src/main/java/org/websoso/WSSServer/repository/UserNovelAttractivePointRepository.java
> +    void deleteByAttractivePointsAndUserNovel(Set<AttractivePoint> attractivePoints, UserNovel userNovel);
P5; 오.. delete 작업을 쿼리로 하는 것 처음 보게 됐네요 신기합니다 굿 👍

2024-07-17 13:39 UTC, rinarina0429 commented on src/main/java/org/websoso/WSSServer/repository/UserNovelAttractivePointRepository.java
> +    void deleteByAttractivePointsAndUserNovel(Set<AttractivePoint> attractivePoints, UserNovel userNovel);
for문으로 리스트 delete를 진행하면 쿼리문이 많이 날아가게 돼서 쿼리문으로 작성했숨니다!

2024-07-29 18:12 UTC, Kim-TaeUk commented on src/main/java/org/websoso/WSSServer/dto/userNovel/UserNovelUpdateRequest.java
> +        List<Integer> keywordIds
q3; 
필드를 기준으로 개행하는 것은 어떤가요!
```suggestion
        @UserNovelRatingConstraint
        @ColumnDefault("0.0")
        Float userNovelRating,
        
        @NotNull(message = "읽기 상태는 null일 수 없습니다.")
        ReadStatus status,
        
        @Pattern(regexp = "\\d{4}-\\d{2}-\\d{2}", message = "시작 날짜는 yyyy-MM-dd 형식이어야 합니다.")
        String startDate,
        
        @Pattern(regexp = "\\d{4}-\\d{2}-\\d{2}", message = "종료 날짜는 yyyy-MM-dd 형식이어야 합니다.")
        String endDate,
        
        @JsonSetter(nulls = Nulls.AS_EMPTY)
        @Size(max = 3, message = "매력 포인트는 최대 3개까지 가능합니다.")
        List<String> attractivePoints,
        
        @JsonSetter(nulls = Nulls.AS_EMPTY)
        @Size(max = 10, message = "키워드는 최대 10개까지 가능합니다.")
        List<Integer> keywordIds
```

2024-07-29 18:23 UTC, Kim-TaeUk commented on src/main/java/org/websoso/WSSServer/repository/UserNovelAttractivePointRepository.java
> +    void deleteByAttractivePointsAndUserNovel(Set<AttractivePoint> attractivePoints, UserNovel userNovel);
q;
많은 delete 쿼리로 인해 성능 저하를 고려해서 벌크 연산을 도입하신 것 같은데,
벌크 연산은 영속성 컨텍스트를 거치지 않고 DB에 바로 쿼리를 실행하기 때문에 영속성 컨텍스트와 DB의 싱크가 맞지 않아서 동기화를 통해 일관성을 보장해주는 것으로 알고 있습니다.

보통 clearAutomatically를 true로 설정해주거나 하는 방식을 통해 일관성을 지켜주는데, 필요없다고 생각하셔서 사용하지 않으신건가요?

2024-07-29 18:24 UTC, Kim-TaeUk commented on src/main/java/org/websoso/WSSServer/repository/UserNovelKeywordRepository.java
> +    void deleteByKeywordsAndUserNovel(Set<Keyword> keywords, UserNovel userNovel);
q;
요기도 위랑 같은 질문입니다~

2024-07-29 18:37 UTC, Kim-TaeUk commented on src/main/java/org/websoso/WSSServer/service/UserNovelService.java
> +        LocalDate endDate = request.endDate() == null ? null : convertToLocalDate(request.endDate());
p5;
개행 추가 하는거 어떠신가요?
삼항 연산자 쓸 때 어떻게 쓰면 가독성이 좋을까 찾아보다가 하나 남깁니다! (요기 말고 아래에도 삼항 연산자가 있네요)
[https://medium.com/hayanmind-tech-blog-kr/3항-연산자의-재발견-a3f815bcdbb8](https://medium.com/hayanmind-tech-blog-kr/3%ED%95%AD-%EC%97%B0%EC%82%B0%EC%9E%90%EC%9D%98-%EC%9E%AC%EB%B0%9C%EA%B2%AC-a3f815bcdbb8)

2024-07-29 18:40 UTC, Kim-TaeUk commented on src/main/java/org/websoso/WSSServer/service/UserNovelService.java
> +        }
p2;
여기 null로 받고 다시 체크해서 익셉션 던지지 말고 바로 던져도 되지 않나요?

2024-07-29 18:42 UTC, Kim-TaeUk commented on src/main/java/org/websoso/WSSServer/service/UserNovelService.java
> +        }
q;
평가한 적이 없기 때문에 `작품 평가 생성 API`를 호출해야 하는데 `작품 평가 수정 API`를 호출한 경우에 터뜨리는 걸까요?

2024-07-29 18:52 UTC, Kim-TaeUk commented on src/main/java/org/websoso/WSSServer/dto/userNovel/UserNovelUpdateRequest.java
> +        @JsonSetter(nulls = Nulls.AS_EMPTY)
q;
이건 어떤 의도로 쓰인건가요?

2024-07-29 18:53 UTC, Kim-TaeUk commented on src/main/java/org/websoso/WSSServer/dto/userNovel/UserNovelUpdateRequest.java
> +        @ColumnDefault("0.0")
q;
`@ColumnDefault`는 어떤 의도로 쓰인걸까요?

2024-07-29 18:55 UTC, Kim-TaeUk commented on src/main/java/org/websoso/WSSServer/dto/userNovel/UserNovelUpdateRequest.java
> +        @UserNovelRatingConstraint
q;
userNovelRating이 명세에는 nullable이라고 안 적혀있는데 null이 가능한가요?

2024-07-29 19:01 UTC, Kim-TaeUk commented on src/main/java/org/websoso/WSSServer/dto/userNovel/UserNovelUpdateRequest.java
> +        String endDate,
p2;
정규 표현식을 통해 포맷에 맞는 형식인지 검사하고 있는데, 유효한 날짜인지에 대한 검증도 이루어지면 좋겠네요!

예를 들어 `2024-02-50`처럼 유효하지 않은 request가 온다면 `@Pattern`에 의해서 검증되지 않고, service layer에서 사용하는 convertToLocalDate메서드의 LocalDate.parse 오류가 발생할 것 같아요.

2024-07-29 19:05 UTC, Kim-TaeUk commented on src/main/java/org/websoso/WSSServer/service/UserNovelService.java
> +                .collect(Collectors.toSet());
오 중복 방지를 위해 Set을 사용한 것인가요?

JPQL의 IN 절에서 List 뿐만 아니라 Collection 타입을 모두 사용 가능하기에 Set을 사용할 수 있다는 사실도 알아가네요 ^_^
(PR에 작성해서 공유하면 더 좋을 것 같아요~ 참고한 레퍼런스가 있다면 같이!)

2024-07-29 19:07 UTC, Kim-TaeUk requested changes
고생하셨습니다. 코멘트 남겨두었습니다. 좀 많이 ㅎㅎ

2024-07-29 19:08 UTC, Kim-TaeUk commented on src/main/java/org/websoso/WSSServer/repository/UserNovelAttractivePointRepository.java
> +    void deleteByAttractivePointsAndUserNovel(Set<AttractivePoint> attractivePoints, UserNovel userNovel);
리뷰 때문에 unresolve 했습니다~

2024-07-30 12:10 UTC, rinarina0429 commented on src/main/java/org/websoso/WSSServer/dto/userNovel/UserNovelUpdateRequest.java
> +        List<Integer> keywordIds
좋습니다!! 피드 등 다른 dto와 일관성이 안맞다고 생각해 개행을 추가하지 않았었는데 Notice에는 추가되어 있었네요. 나중에 dto 리팩토링 시에 통일시키면 좋을 것 같아요! 일단 요기 개행 추가해뒀습니다~

2024-07-30 12:13 UTC, rinarina0429 commented on src/main/java/org/websoso/WSSServer/service/UserNovelService.java
> +        }
해당 방식으로 수정했습니다!!

2024-07-30 12:13 UTC, rinarina0429 commented on src/main/java/org/websoso/WSSServer/service/UserNovelService.java
> +        }
네 맞습니다!

2024-07-30 12:29 UTC, rinarina0429 commented on src/main/java/org/websoso/WSSServer/dto/userNovel/UserNovelUpdateRequest.java
> +        @JsonSetter(nulls = Nulls.AS_EMPTY)
사용자가 attractivePoints나 keywordIds를 입력하지 않으면 null값이 아니라 빈 리스트가 들어가게 처리했습니다

2024-07-30 12:50 UTC, rinarina0429 commented on src/main/java/org/websoso/WSSServer/service/UserNovelService.java
> +                .collect(Collectors.toSet());
채은언니 피드 수정 API에서 set을 사용해서 알아보다 중복 제거가 가능한게 커서 set을 사용했습니다!
https://www.baeldung.com/java-choose-list-set-queue-map
요기서 각 시간복잡도를 잘 정리해주는데 ArrayList보다는 Set을 사용하는게 성능상에서도 나아보이더라구요

2024-07-30 13:04 UTC, rinarina0429 commented on src/main/java/org/websoso/WSSServer/repository/UserNovelAttractivePointRepository.java
> +    void deleteByAttractivePointsAndUserNovel(Set<AttractivePoint> attractivePoints, UserNovel userNovel);
그렇네요!! 몰라서 안쓴거였습니다. 새롭게 알게되네요
`@Modifying(clearAutomatically = true, flushAutomatically = true)` 옵션 붙여줬습니다!

- 참고
https://devhyogeon.tistory.com/4
https://velog.io/@gruzzimo/JPA-Modifying%EC%9D%98-flushAutomatically-%EC%98%B5%EC%85%98%EC%9D%80-%EC%96%B8%EC%A0%9C-%EC%93%B0%EC%A7%80

2024-07-30 13:05 UTC, rinarina0429 commented on src/main/java/org/websoso/WSSServer/repository/UserNovelKeywordRepository.java
> +    void deleteByKeywordsAndUserNovel(Set<Keyword> keywords, UserNovel userNovel);
마찬가지로 옵션 추가해줬습니다!!

2024-07-30 13:15 UTC, rinarina0429 commented on src/main/java/org/websoso/WSSServer/service/UserNovelService.java
> +        LocalDate endDate = request.endDate() == null ? null : convertToLocalDate(request.endDate());
이게 굳이 개행을 추가하기엔 특히 아래 경우에는 줄 자체가 짧고 간단하게 끝나기도 하고... 개행으로 요소를 구분하기도 하고... 하지만? 코멘트가 달렸으니 해보기나 할까..? 하고 해봤는데! 진짜 가독성이 훨씬 좋아지네요??? 너무 좋슴니다 아래까지 모두 적용 완입니당!!!

2024-07-30 13:16 UTC, rinarina0429 commented on src/main/java/org/websoso/WSSServer/dto/userNovel/UserNovelUpdateRequest.java
> +        @UserNovelRatingConstraint
null이 가능하지는 않습니다,, 위에 코멘트로 한번 확인 부탁드립니다!!

2024-07-30 13:23 UTC, rinarina0429 commented on src/main/java/org/websoso/WSSServer/dto/userNovel/UserNovelUpdateRequest.java
> +        @UserNovelRatingConstraint
위 코멘트로 확인해주세요!!

2024-07-30 13:29 UTC, rinarina0429 commented on src/main/java/org/websoso/WSSServer/dto/userNovel/UserNovelUpdateRequest.java
> +        @JsonSetter(nulls = Nulls.AS_EMPTY)
nullable한걸 API에 안적어둬서 의도가 불분명했던 것 같네요 ㅜㅜ 명세서에 추가해뒀습니다!

2024-07-30 13:30 UTC, rinarina0429 commented on src/main/java/org/websoso/WSSServer/dto/userNovel/UserNovelUpdateRequest.java
> +        @ColumnDefault("0.0")
nullable한데, 명세서에 적어두지 못했네요ㅜㅜ 추가해뒀습니다. 작품 평가, 즉 Rating의 경우 평가하지 않으면 null이 아니라 0.0으로 들어가야 하기 때문에 ColumnDefault를 사용했습니다.

2024-07-30 13:59 UTC, rinarina0429 commented on src/main/java/org/websoso/WSSServer/dto/userNovel/UserNovelUpdateRequest.java
> +        String endDate,
그렇네요! 너무 좋은 의견입니다. 아래와 같이 코드 추가했습니다~!
```java
@AssertTrue(message = "시작 날짜는 유효한 날짜여야 합니다.")
public boolean isStartDateValid() {
    return startDate == null || isValidDate(startDate);
}

@AssertTrue(message = "종료 날짜는 유효한 날짜여야 합니다.")
public boolean isEndDateValid() {
    return endDate == null || isValidDate(endDate);
}

@AssertTrue(message = "종료 날짜는 시작 날짜 이후여야 합니다.")
public boolean isEndDateEqualOrAfterToEndDate() {
    if (startDate != null && endDate != null && isValidDate(startDate) && isValidDate(endDate)) {
        LocalDate start = LocalDate.parse(startDate);
        LocalDate end = LocalDate.parse(endDate);
        return end.isEqual(start) || end.isAfter(start);
    }
    return true;
}

private boolean isValidDate(String dateString) {
    try {
        LocalDate.parse(dateString);
        return true;
    } catch (Exception e) {
        return false;
    }
}
```

2024-07-31 17:40 UTC, Kim-TaeUk commented on src/main/java/org/websoso/WSSServer/service/UserNovelService.java
> +                .collect(Collectors.toSet());
굿입니다~
Set 자료구조가 중복을 허용하지 않는데, 순서를 보장하지 않는다는 성질도 있어서 순서 보장이 필요할 때는 사용하면 안됩니닷.
지금 상황에서는 순서를 보장해야하는 상황은 아니어서 괜찮겠네요! 
👍 👍

2024-07-31 17:42 UTC, Kim-TaeUk commented on src/main/java/org/websoso/WSSServer/service/UserNovelService.java
> +                .collect(Collectors.toSet());
확인하시면 resolve 해주세요!

2024-07-31 17:44 UTC, Kim-TaeUk commented on src/main/java/org/websoso/WSSServer/service/UserNovelService.java
> +        LocalDate endDate = request.endDate() == null ? null : convertToLocalDate(request.endDate());
삼항 연산자에 validate하는 메서드를 사용하는 경우도 있어서 좀 길어지면 가독성이 떨어지는 경향이 있더라구요.
human-readable한 코드를 작성하면 좋을 것 같아서 제안했습니다!

2024-07-31 17:47 UTC, Kim-TaeUk commented on src/main/java/org/websoso/WSSServer/dto/userNovel/UserNovelUpdateRequest.java
> +        @ColumnDefault("0.0")
nullable한데 null이 아니라 0.0으로 넣어줘야한다는게 잘 이해가 가지 않는데요,

null로 저장해야 하는 상황이 없다면 nullable하지 않게 설정해주는게 좋지 않을까요?

2024-07-31 17:52 UTC, Kim-TaeUk commented on src/main/java/org/websoso/WSSServer/dto/userNovel/UserNovelUpdateRequest.java
> +        @JsonSetter(nulls = Nulls.AS_EMPTY)
음 굳이 그런 상황이라면 굳이 Null을 받지 말고 빈 리스트로 받는게 낫지 않을까요?
클라이언트에서 빈 리스트로 줄 수 있는데 굳이 null로 받고 그걸 다시 빈 리스트로 셋해주는게 불필요한 것 같아요.

컬렉션 api 사용할 때는 NPE 방지(안정성), 가독성을 위해 null 대신 빈 컬렉션을 사용하는게 더 나을 것 같아요.

2024-07-31 19:13 UTC, Kim-TaeUk commented on src/main/java/org/websoso/WSSServer/dto/userNovel/UserNovelUpdateRequest.java
> +        String endDate,
음...!! 날짜 타입으로 json 주고 받을 때 LocalDate로 주고받는게 좋을 것 같은데요!
(저도 공지사항 api에서는 자세하게 알기 전이라 적용되어있지 않기는 합니다. 추후 리팩터링 예정..!)

String으로 받고 다시 LocalDate로 직렬화하는 과정이 번거롭기도하고, validation을 위해 spring bean validation에서 제공해주는 어노테이션이 있음에도 지금처럼 만들어써야하는 것이 번거롭기도 하고요.
(번거로움도 있지만 사람이 만들다보니 라이브러리에 비해 안정성이 떨어지기도 합니다..ㅜ)

---
레퍼런스 드릴테니 한 번 확인해보세욥! 공부했던 자료들이라 다행히도 레퍼런스가 다 남아있네요.

`ref1`: https://docs.spring.io/spring-framework/docs/3.2.3.RELEASE/javadoc-api/org/springframework/format/annotation/DateTimeFormat.html
-> Spring Framework에서 제공하는 annotation: `@DateTimeFormat`

`ref2`: https://www.javadoc.io/doc/com.fasterxml.jackson.core/jackson-annotations/2.9.8/com/fasterxml/jackson/annotation/JsonFormat.html
-> Jackson 라이브러리에서 제공하는 annotation: `@JsonFormat`

`ref3`: https://jakarta.ee/specifications/bean-validation/3.0/apidocs/jakarta/validation/constraints/package-summary
-> Jakarta Bean Validation: `@FutureOrPresent`, `@PastOrPresent`등등

`ref4`: https://jojoldu.tistory.com/361
-> 여러 상황에서의 `@DateTimeFormat`과 `@JsonFormat`

---

Spring에서 response/request dto에서 날짜 관련 프로퍼티의 타입으로 주로 사용하는 `@DateTimeFormat`과 `@JsonFormat`에 대해 호돌맨 님이 `ref4`에서 분석(실험(?))하는거라 쭉 한 번 읽어보시는걸 추천하고,
`@DateTimeFormat`과 `@JsonFormat` 자체가 어떻게 정의되어 있는지 확인해보면 좋을 것 같아서 `ref1`, `ref2`도 링크 추가해뒀습니다.

`@NotNull`, `@Min`과 같은 bean validation 어노테이션은 자주 사용하는데, 날짜 관련 어노테이션은 익숙하지 않아서 사용하지 않는 것 같아서(물론 저 포함입니다), `ref3`으로 함께 공유합니다.

---

Spring에서 날짜 타입을 불필요하게 직렬화하는 로직이 service layer 등에 침투되어 있는데요! (당연히 저 포함입니다 ㅋㅋ)
저희 팀에서 우아하게 사용할 수 있는 레퍼런스들이라고 생각해서 채은쓰도 멘션 겁니다~!
나경쓰가 이번 PR에서 멋지게 보여주시져 ㅋㅋ
@rinarina0429 @ChaeAg

2024-08-01 11:02 UTC, rinarina0429 commented on src/main/java/org/websoso/WSSServer/dto/userNovel/UserNovelUpdateRequest.java
> +        @JsonSetter(nulls = Nulls.AS_EMPTY)
그렇네요! 그럼 null로 왔을 때 사용되는 `@JsonSetter(nulls = Nulls.AS_EMPTY)`도 없애고 null로 주면 바로 exception을 터트리는게 나을까요?

2024-08-01 11:04 UTC, rinarina0429 commented on src/main/java/org/websoso/WSSServer/dto/userNovel/UserNovelUpdateRequest.java
> +        @ColumnDefault("0.0")
음 그러니까 nullable하다기 보다는 사용자가 평점을 넣을 필요는 없다는게 맞는 말이었겠네요! 그럼 nullable로 설정하지 않고 사용자가 평가하지 않은 경우 0.0으로 달라고 하겠습니다! 여기도 마찬가지로 null로 받으면 exception을 터트리면 되겠죠?

2024-08-01 13:26 UTC, rinarina0429 commented on src/main/java/org/websoso/WSSServer/dto/userNovel/UserNovelUpdateRequest.java
> +        String endDate,
너무나도 좋은 의견입니다!! 한번 사용하니 왜 String으로 주고 받았지..? 라는 생각이 드네요 허허
+ 저희가 별개의 포맷을 사용하지 않고 스프링의 LocalDate 기본 포맷("yy-MM-dd")을 사용해서 별개의 어노테이션을 붙여줄 필요는 없다고 합니다!
하여 String 모두 LocalDate로 바꾸고 post, put에서 LocalDate로 바로 받을 수 있도록, get에서도 바로 LocalDate로 전달하도록 수정했습니다. 또한 startDate, endDate에 @PastOrPresent 어노테이션 추가하여 @AssertTrue는 isEndDateEqualOrAfterToEndDate()만 남겨두었습니다!

2024-08-01 13:29 UTC, Kim-TaeUk commented on src/main/java/org/websoso/WSSServer/dto/userNovel/UserNovelUpdateRequest.java
> +        @JsonSetter(nulls = Nulls.AS_EMPTY)
> 음 굳이 그런 상황이라면 굳이 Null을 받지 말고 빈 리스트로 받는게 낫지 않을까요?

`@NotNull` 쓰시면 될 것 같은데유?

2024-08-01 13:30 UTC, Kim-TaeUk commented on src/main/java/org/websoso/WSSServer/dto/userNovel/UserNovelUpdateRequest.java
> +        @ColumnDefault("0.0")
넵 not null로 처리하면 되겠네용

2024-08-01 13:31 UTC, Kim-TaeUk commented on src/main/java/org/websoso/WSSServer/dto/userNovel/UserNovelUpdateRequest.java
> +        @UserNovelRatingConstraint
not null이니까
UserNovelRatingValidator에서 null인 경우 true로 처리하고 있는 것도 확인해주세요

2024-08-01 13:39 UTC, Kim-TaeUk commented on src/main/java/org/websoso/WSSServer/dto/userNovel/UserNovelUpdateRequest.java
> +        @JsonSetter(nulls = Nulls.AS_EMPTY)
움 null로 받을 때 빈리스트로 초기화하는 것도 나쁘지 않은거 같긴 한데....
클라랑 얘기 한 번 해보시는거 어떤가유?

2024-08-01 13:47 UTC, Kim-TaeUk commented on src/main/java/org/websoso/WSSServer/dto/userNovel/UserNovelUpdateRequest.java
> +        String endDate,
`@AssertTrue`로 validate한 부분 굿입니다!
같은 로직을 수행해야할 곳이 많다면 재사용성을 고려해서 추후에 custom annotation으로 만들어도 좋을 것 같네요.

---

> 스프링의 LocalDate 기본 포맷("yy-MM-dd")을 사용해서 별개의 어노테이션을 붙여줄 필요는 없다고 합니다!

Spring에서 LocalDate의 기본 포맷을 yy-MM-dd로 사용한다는 점을 찾아보는데 찾지 못해서요, 
혹시 이건 어떻게 확인할 수 있을까요??

2024-08-01 13:50 UTC, Kim-TaeUk commented on src/main/java/org/websoso/WSSServer/repository/UserNovelAttractivePointRepository.java
> +    void deleteByAttractivePointsAndUserNovel(Set<AttractivePoint> attractivePoints, UserNovel userNovel);
넵 굿입니다~~

2024-08-01 13:51 UTC, Kim-TaeUk commented on src/main/java/org/websoso/WSSServer/domain/UserNovel.java
> +    @OneToMany(mappedBy = "userNovel", cascade = ALL, fetch = FetchType.EAGER, orphanRemoval = true)
페치 전략을 즉시 로딩으로 변경한 이유는 무엇인가요?

2024-08-01 14:18 UTC, rinarina0429 commented on src/main/java/org/websoso/WSSServer/dto/userNovel/UserNovelUpdateRequest.java
> +        String endDate,
- [오라클 공식문서_Class LocalDate](https://docs.oracle.com/en/java/javase/20/docs/api/java.base/java/time/LocalDate.html)
- [오라클 공식문서_Class DateTimeFormatter](https://docs.oracle.com/en/java/javase/20/docs/api/java.base/java/time/format/DateTimeFormatter.html)
- [Baeldung](https://www.baeldung.com/java-format-localdate-iso-8601-t-z)
공식적인 자료를 찾아보자면 위의 자료들에서 찾아볼 수 있고, 구글에 **"spring localdate 기본 형식"**으로만 검색해도 많이 나옵니다!

2024-08-01 14:27 UTC, rinarina0429 commented on src/main/java/org/websoso/WSSServer/dto/userNovel/UserNovelUpdateRequest.java
> +        @ColumnDefault("0.0")
@NotNull 붙여줬습니다!

2024-08-01 14:27 UTC, rinarina0429 commented on src/main/java/org/websoso/WSSServer/dto/userNovel/UserNovelUpdateRequest.java
> +        @UserNovelRatingConstraint
네 해당 로직 제거 완입니다~

2024-08-01 14:48 UTC, rinarina0429 commented on src/main/java/org/websoso/WSSServer/dto/userNovel/UserNovelUpdateRequest.java
> +        @JsonSetter(nulls = Nulls.AS_EMPTY)
클라에서도 널보다 빈 리스트를 주는게 좋다 하여! 해당 방식으로 수정했습니다~

2024-08-01 14:51 UTC, Kim-TaeUk commented on src/main/java/org/websoso/WSSServer/dto/userNovel/UserNovelUpdateRequest.java
> +        String endDate,
yyyy-MM-dd 아닌가여 ㅎㅎ,,, 
yyyy-MM-dd로 사용해야하는데 yy-MM-dd가 디폴트라 포맷팅할 필요 없다고 하셔서 무슨 말인가 했습니다

2024-08-01 15:45 UTC, rinarina0429 commented on src/main/java/org/websoso/WSSServer/dto/userNovel/UserNovelUpdateRequest.java
> +        @UserNovelRatingConstraint
@NotNull 어노테이션과 순서를 따로 지정할 수 없는 것으로 알고 있는데, null 값을 넣었을 시에 @NotNull이 아니라 customValidator를 먼저 거치면 오류 메세지가 정확히 뜨지 않는 문제가 있어 해당 로직은 유지하고 @NotNull만 추가하는 것으로 수정했습니다!

2024-08-01 16:21 UTC, Kim-TaeUk commented on src/main/java/org/websoso/WSSServer/dto/userNovel/UserNovelUpdateRequest.java
> +        @UserNovelRatingConstraint
UserNovelRatingValidator에서 null을 검사하면 되지 않을까요?

2024-08-02 13:06 UTC, rinarina0429 commented on src/main/java/org/websoso/WSSServer/dto/userNovel/UserNovelUpdateRequest.java
> +        @UserNovelRatingConstraint
두가지 어노테이션의 역할을 분리해줬습니다!

2024-08-02 13:07 UTC, rinarina0429 commented on src/main/java/org/websoso/WSSServer/dto/userNovel/UserNovelUpdateRequest.java
> +        String endDate,
헉 오타 때문에 잔뜩 찾아보셨겠네요 죄송합니다 허허허ㅜㅜ

2024-08-02 13:15 UTC, rinarina0429 commented on src/main/java/org/websoso/WSSServer/domain/UserNovel.java
> +    @OneToMany(mappedBy = "userNovel", cascade = ALL, fetch = FetchType.EAGER, orphanRemoval = true)
전에 얘기 나눴던 대로 `@Modifying(clearAutomatically = true, flushAutomatically = true)` 해당 어노테이션을 거치며 LazyInitializationException이 터지는 것을 방지하기 위해 설정하였습니다.

하지만 즉시로딩으로 바꾸는 것이 좋은 방법 같지는 않아 다음과 같은 fetch join도 사용해 보았는데요
```java
@Query("SELECT un FROM UserNovel un " +
       "LEFT JOIN FETCH un.userNovelAttractivePoints unattractivePoints " +
       "LEFT JOIN FETCH unattractivePoints.attractivePoint " +
       "LEFT JOIN FETCH un.userNovelKeywords unKeywords " +
       "LEFT JOIN FETCH unKeywords.keyword " +
       "WHERE un.novel = :novel AND un.user = :user")
Optional<UserNovel> findByNovelAndUserWithAssociations(Novel novel, User user);
```
Hibernate.initialize()를 사용했을 때처럼 오류가 나지 않게 되더라도 쿼리문의 결과가 제대로 나오지 않았습니다.
기존에 `@Modifying(clearAutomatically = true, flushAutomatically = true)` 해당 어노테이션이 걸려있는 두 쿼리문을 두 함수로 나눠뒀었는데, 하나는 정상 작동하고, 다음 함수로 넘어가서 결과를 제대로 불러오지 못한다는 사실 때문에 한 함수 내에서 호출하면 제대로 된 결과가 나오는 것을 알게 되어,
결과적으로는 다른건 건드리지 않고 지연로딩으로 복구하고 함수의 구조만 변경하는 리팩토링을 진행했습니다.

2024-08-03 09:14 UTC, Kim-TaeUk commented on src/main/java/org/websoso/WSSServer/domain/UserNovel.java
> +    @OneToMany(mappedBy = "userNovel", cascade = ALL, fetch = FetchType.EAGER, orphanRemoval = true)
하나의 메서드로 묶어서 트랜잭션을 묶어 처리하는 의도로 LazyInitializationException이 발생하지 않게 한 것 같네욥

`userNovelAttractivePointRepository.deleteByAttractivePointsAndUserNovel`랑 `userNovelKeywordRepository.deleteByKeywordsAndUserNovel` 둘 다에 @Transactional하고 @Modyfing이 걸려있어서 한 메서드로 묶어도 LazyInitializationException이 터질거라고 생각이 드는데... 

혹시 안터지는 이유를 아시나요??..

2024-08-04 10:08 UTC, rinarina0429 commented on src/main/java/org/websoso/WSSServer/domain/UserNovel.java
> +    @OneToMany(mappedBy = "userNovel", cascade = ALL, fetch = FetchType.EAGER, orphanRemoval = true)
아뇨 정확히 뭐가 어떻게 되는건지 알아서 이걸로 아티클을 쓰고 싶어서 찾아보는 중인데 아직 아이러니 하네요... 혹시 아시나요? 찾으면 공유하도록 하겠습니다

2024-08-04 10:12 UTC, Kim-TaeUk commented on src/main/java/org/websoso/WSSServer/domain/UserNovel.java
> +    @OneToMany(mappedBy = "userNovel", cascade = ALL, fetch = FetchType.EAGER, orphanRemoval = true)
저도 디버깅해보진 않았고, 생각한 것과 다른 결과가 나와서 매우매우 궁금한데요!!

일단 잘 작동하니,, resolve하고
이유 찾게 되면 아티클 작성 전이라도 공유해주심 감사하겠습니다 ^^

2024-08-04 10:13 UTC, Kim-TaeUk approved these changes

2024-08-04 10:13 UTC, merged