[FIX] 키워드 검색 시 수정사항 반영
Team-WSS/WSS-Server pull request #109
Opened 2024-07-17 05:58 UTC by rinarina0429

## Related Issue

- feat/#108 -> dev
- close #108 

## Key Changes

키워드 검색 뷰가 수정되었습니다.
이 과정에서 키워드 카테고리 별 이미지를 함께 전달해야 돼 해당 사항을 반영합니다.

## To Reviewers

## References

2024-07-17 07:20 UTC, ChaeAg approved these changes
굿입니다용 !!

2024-07-19 15:41 UTC, Kim-TaeUk commented on src/main/java/org/websoso/WSSServer/service/KeywordService.java
> +                        sortByCategory(category, searchKeyword(query))))
p1;
여기 searchKeyword(query)가 map 메서드 내에서 반복적으로 중복 호출될 것 같아요. 
카테고리의 수만큼 검색을 하게 될 것 같은데, 검색은 한 번만/이후 사용은 캐싱된걸로 할 수 있을 것 같아욥

2024-07-19 15:44 UTC, Kim-TaeUk requested changes
코멘트 남겨두었습니다!

2024-07-21 11:42 UTC, rinarina0429 commented on src/main/java/org/websoso/WSSServer/service/KeywordService.java
> +                        sortByCategory(category, searchKeyword(query))))
그렇네요! 해당 사항 반영해 수정하였습니다~

2024-07-21 11:44 UTC, Kim-TaeUk commented on src/main/java/org/websoso/WSSServer/service/KeywordService.java
> +                        sortByCategory(category, searchKeyword(query))))
척하면 척이시군요 👍

2024-07-21 11:44 UTC, Kim-TaeUk approved these changes
굿입니다 어푸룹~ 👍

2024-07-21 11:46 UTC, merged