[FEAT] 소소피드 댓글 CRUD API 구현
Team-WSS/WSS-Server pull request #113
Opened 2024-07-19 02:13 UTC by ChaeAg

## Related Issue

- feat/#68 -> dev
- close #68

## Key Changes

### 소소피드 댓글 CRUD API를 구현했습니다.

🔑
- 댓글은 무조건 로그인 한 유저만이 확인이 가능합니다. -> 댓글은 특정 소소피드에 들어가서 볼 수 있기 때문에 비로그인 유저는 접근 불가능
- 댓글을 작성한 유저와 차단 관계이면 그 댓글은 보이지 않습니다.
- 여러번 신고를 받아, 숨김 처리가 된 댓글은 보이지 않습니다.
- 특정 피드의 **댓글 수**는 차단, 숨김 여부와 상관 없이 실제 있는 전체 댓글 개수를 나타내는 것입니다. (기획과 이야기 O)

## To Reviewers

현재 PR이 열려있는 소소피드 전체 조회 API를 rebase 해서 수정사항이 섞여있는데요!
해당 부분을 코멘트로 남겨놓을테니 제외하고 봐주시면 될 것 같습니다!

## References

2024-07-19 02:20 UTC, ChaeAg commented on src/main/java/org/websoso/WSSServer/config/SecurityConfig.java
> +            "/feeds"
**소소피드 전체 조회 API 수정사항 (제외하고 봐주세요)**

2024-07-19 02:20 UTC, ChaeAg commented on src/main/java/org/websoso/WSSServer/controller/FeedController.java
> +    }
**소소피드 전체 조회 API 수정사항 (제외하고 봐주세요)**

2024-07-19 02:20 UTC, ChaeAg commented on src/main/java/org/websoso/WSSServer/dto/feed/FeedInfo.java
**소소피드 전체 조회 API 수정사항 (제외하고 봐주세요)**

2024-07-19 02:20 UTC, ChaeAg commented on src/main/java/org/websoso/WSSServer/dto/feed/FeedsGetResponse.java
**소소피드 전체 조회 API 수정사항 (제외하고 봐주세요)**

2024-07-19 02:20 UTC, ChaeAg commented on src/main/java/org/websoso/WSSServer/repository/FeedCategoryRepository.java
**소소피드 전체 조회 API 수정사항 (제외하고 봐주세요)**

2024-07-19 02:20 UTC, ChaeAg commented on src/main/java/org/websoso/WSSServer/repository/FeedRepository.java
**소소피드 전체 조회 API 수정사항 (제외하고 봐주세요)**

2024-07-19 02:20 UTC, ChaeAg commented on src/main/java/org/websoso/WSSServer/service/FeedCategoryService.java
**소소피드 전체 조회 API 수정사항 (제외하고 봐주세요)**

2024-07-19 02:20 UTC, ChaeAg commented on src/main/java/org/websoso/WSSServer/service/FeedService.java
> +    }
**소소피드 전체 조회 API 수정사항 (제외하고 봐주세요)**

2024-07-19 02:20 UTC, ChaeAg commented on src/main/java/org/websoso/WSSServer/service/FeedService.java
> +    }
**소소피드 전체 조회 API 수정사항 (제외하고 봐주세요)**

2024-07-19 15:19 UTC, Kim-TaeUk reviewed
커밋도 중복돼서 전체 조회 API dev에 머지되면 확인해보겠습니닷

2024-08-01 06:26 UTC, rinarina0429 reviewed
CRUD 한번에 구현하셨네요~~ 수고하셨습니다!!

2024-08-01 06:26 UTC, rinarina0429 commented on src/main/java/org/websoso/WSSServer/service/CommentService.java
> +    }
오앙 진짜 초대박 깔꼼해요

2024-08-01 06:26 UTC, rinarina0429 commented on src/main/java/org/websoso/WSSServer/exception/error/CustomCommentError.java
> +    COMMENT_NOT_BELONG_TO_FEED("COMMENT-002", "댓글이 지정된 피드에 속하지 않습니다.", NOT_FOUND);
p3; NOT_FOUND 말고 CONFLICT는 어떠신가요?

2024-08-02 16:16 UTC, ChaeAg commented on src/main/java/org/websoso/WSSServer/exception/error/CustomCommentError.java
> +    COMMENT_NOT_BELONG_TO_FEED("COMMENT-002", "댓글이 지정된 피드에 속하지 않습니다.", NOT_FOUND);
헛 저는 `해당 피드 댓글 목록에서 해당 댓글을 찾을 수 없다` 는 의미에서 `NOT FOUND` 를 사용했는데용!
`CONFLICT` 를 제안하시는 이유가 있을까유?

2024-08-04 09:38 UTC, Kim-TaeUk commented on src/main/java/org/websoso/WSSServer/domain/Comment.java
> +@DynamicInsert
q;
`@DynamicInsert` 사용한 이유가 무엇인가요?

2024-08-04 09:40 UTC, Kim-TaeUk commented on src/main/java/org/websoso/WSSServer/dto/comment/CommentCreateRequest.java
> +        @NotBlank(message = "댓글 내용은 비어 있거나, 공백일 수 없습니다.")
p3;
`@NotBlank`가 null도 검증해서, message에 포함되는게 어떨까요?

2024-08-04 09:42 UTC, Kim-TaeUk commented on src/main/java/org/websoso/WSSServer/domain/Novel.java
>      private List<UserNovel> userNovels = new ArrayList<>();
UserNovel이 Novel 개인 소유가 아니라 User도 가지고 있어서 문제가 있어보이는데 어떻게 생각하시나요?

2024-08-04 09:44 UTC, Kim-TaeUk commented on src/main/java/org/websoso/WSSServer/domain/Comment.java
> +        if (!Objects.equals(this.userId, userId)) {
q;
비회원인 경우 null이라서 Objects.equals() 사용하신건가요?

2024-08-04 09:51 UTC, Kim-TaeUk commented on src/main/java/org/websoso/WSSServer/dto/comment/CommentGetResponse.java
> +        String createdDate,
p2;
[요거](https://github.com/Team-WSS/WSS-Server/pull/107#discussion_r1698988251) 한 번 확인해주세요!

LocalDate 타입으로 주고 받고, 어노테이션(JsonFormat이나 DateTimeFormat)으로 세팅해주는거 제안합니다~

2024-08-04 09:52 UTC, Kim-TaeUk commented on src/main/java/org/websoso/WSSServer/dto/comment/CommentUpdateRequest.java
> +        @NotBlank(message = "댓글 내용은 비어 있거나, 공백일 수 없습니다.")
p3;
@NotBlank가 null도 검증해서, message에 포함되는게 어떨까요?

요기도 같은 제안입니다.

2024-08-04 09:54 UTC, Kim-TaeUk commented on src/main/java/org/websoso/WSSServer/exception/error/CustomCommentError.java
> +    COMMENT_NOT_BELONG_TO_FEED("COMMENT-002", "댓글이 지정된 피드에 속하지 않습니다.", NOT_FOUND);
리소스 충돌이랑은 거리가 있고 404에 알맞는 케이스 같아서 
저두 그대로가 괜찮다고 생각하는데 409로 제시하시는 이유가 궁금하네유~

2024-08-04 09:58 UTC, Kim-TaeUk commented on src/main/java/org/websoso/WSSServer/domain/Comment.java
> +    public void validateUserAuthorization(Long userId, Action action) {
q;
validateUserAuthorization 메서드가 사용된 곳을 확인해봤는데 action으로 로직으로 쓰이지는 않더라구요.
action의 사용 목적은 message 지정하기 위함인가요??

2024-08-04 09:59 UTC, Kim-TaeUk commented on src/main/java/org/websoso/WSSServer/service/CommentService.java
> +        comment.updateContent(commentContent);
p4;
메서드마다 책임을 적절하게 나누어 갖도록 구현했네욥.
개행이 없어도 가독성이 좋아보이는데 개행 삭제는 어떤가요?

deleteComment 메서드도 같은 제안입니다~

2024-08-04 10:03 UTC, Kim-TaeUk commented on src/main/java/org/websoso/WSSServer/service/CommentService.java
> +        comment.updateContent(commentContent);
아래 FeedService의 메인 메서드들에서도요!

2024-08-04 10:05 UTC, Kim-TaeUk commented on src/main/java/org/websoso/WSSServer/service/CommentService.java
> +    }
p3;
stream api랑 filter 사용하면 좀 더 모던 자바스럽게 처리할 수 있을 것 같은데요,
추후에 리팩터링하셔도 될 것 같고 이번 PR에 하셔도 될 것 같고 선택에 맡기겠습니다~

2024-08-04 10:08 UTC, Kim-TaeUk commented on src/main/java/org/websoso/WSSServer/service/FeedService.java
> +    }
p5;
긍정 조건일 때가 사람이 읽기 더 편하다고 생각해서 얼리 리턴하는 것은 어떠하신지...
그저 제안입니다 ^^,,

2024-08-04 10:09 UTC, Kim-TaeUk requested changes
고생하셨습니다 👍 
리뷰 확인해주세요~

2024-08-04 10:27 UTC, rinarina0429 commented on src/main/java/org/websoso/WSSServer/exception/error/CustomCommentError.java
> +    COMMENT_NOT_BELONG_TO_FEED("COMMENT-002", "댓글이 지정된 피드에 속하지 않습니다.", NOT_FOUND);
오호 저는 404의 경우에는 댓글이 데이터베이스에 존재하지 않는 상황을 표현하려는 경우가 더 적합하고,
위와 같은 경우에서는 댓글은 존재하지만, 그것이 클라이언트가 요청한 피드와의 관계가 부정확할 때, 즉 리소스 간의 상태가 일치하지 않는 상황을 나타내려는 경우라고 생각해서 409가 더 잘 맞지 않을까... 생각한건데요
리소스 충돌과는 거리가 있어보이나요?

2024-08-04 10:30 UTC, Kim-TaeUk commented on src/main/java/org/websoso/WSSServer/exception/error/CustomCommentError.java
> +    COMMENT_NOT_BELONG_TO_FEED("COMMENT-002", "댓글이 지정된 피드에 속하지 않습니다.", NOT_FOUND);
400이나 404가 적절한 것 같아요 
보통 PUT 요청으로 넣으려는 리소스가 기존 리소스와 `충돌`할 때 409를 사용한다고 생각해서요!

https://www.webfx.com/web-development/glossary/http-status-codes/what-is-a-409-status-code/
https://developer.mozilla.org/ko/docs/Web/HTTP/Status/409

2024-08-04 10:40 UTC, rinarina0429 commented on src/main/java/org/websoso/WSSServer/exception/error/CustomCommentError.java
> +    COMMENT_NOT_BELONG_TO_FEED("COMMENT-002", "댓글이 지정된 피드에 속하지 않습니다.", NOT_FOUND);
흠 그럼 그대로 404가 좋겠네요!!

2024-08-04 16:55 UTC, ChaeAg commented on src/main/java/org/websoso/WSSServer/dto/comment/CommentCreateRequest.java
> +        @NotBlank(message = "댓글 내용은 비어 있거나, 공백일 수 없습니다.")
앗 `비어있거나` 가 null 일때를 말하는 것이었는데, null 이라고 명시해주는 것이 더 좋은 것 같네요!
반영했습니다!

2024-08-04 16:55 UTC, ChaeAg commented on src/main/java/org/websoso/WSSServer/domain/Comment.java
> +@DynamicInsert
댓글 엔티티의 `isHidden` 컬럼이 default 값이 정해져있고, nullable 하지 않기 때문에 해당 어노테이션을 작성해주어야 아래 `create` 메서드를 통해 댓글 엔티티를 생성할 때 에러가 발생하지 않습니다!

2024-08-04 16:55 UTC, ChaeAg commented on src/main/java/org/websoso/WSSServer/domain/Comment.java
> +    public void validateUserAuthorization(Long userId, Action action) {
네 맞습니다! 에러 메세지에 무슨 작업을 시도했던 것인지 나타내주기 위해 사용했고, 다른 역할은 하지 않습니다!

2024-08-04 16:55 UTC, ChaeAg commented on src/main/java/org/websoso/WSSServer/domain/Comment.java
> +        if (!Objects.equals(this.userId, userId)) {
넵 맞습니다! 래퍼타입(Long)이여서 null일 경우 에러가 발생하더라구요!

2024-08-04 16:55 UTC, ChaeAg commented on src/main/java/org/websoso/WSSServer/domain/Novel.java
>      private List<UserNovel> userNovels = new ArrayList<>();
헉 그렇네요..! 무슨 생각으로 추가했는지 모르겠네요..
cascade 속성 제거했습니다!

2024-08-04 16:55 UTC, ChaeAg commented on src/main/java/org/websoso/WSSServer/dto/comment/CommentGetResponse.java
> +        String createdDate,
헉 태그 해주셨는데 미처 못봤네요.. 너무 늦게 확인해서 죄송합니다 😢
이런 방법이 있었다니 정말 좋습니다!
해당 방식으로 변경해보겠습니다!

2024-08-04 16:55 UTC, ChaeAg commented on src/main/java/org/websoso/WSSServer/dto/comment/CommentUpdateRequest.java
> +        @NotBlank(message = "댓글 내용은 비어 있거나, 공백일 수 없습니다.")
반영했습니다!

2024-08-04 16:55 UTC, ChaeAg commented on src/main/java/org/websoso/WSSServer/service/CommentService.java
> +        comment.updateContent(commentContent);
말씀듣고 제거 해보니 나쁘지 않네요! 가독성이 막 나빠지는 것도 아니고 코드도 줄어들고 👍
필요하다 생각하는 부분 제외하고는 개행 제거 했습니다!

2024-08-04 16:55 UTC, ChaeAg commented on src/main/java/org/websoso/WSSServer/service/CommentService.java
> +    }
저 createdUser가 두번 사용이 되어서 ㅜ 스트림으로 할 수가 없을 것 같아 for문으로 구성했었는데요,
map을 이용하여 해결할 수가 있더군요! 리팩토링 완료했습니다 :>

2024-08-04 16:55 UTC, ChaeAg commented on src/main/java/org/websoso/WSSServer/service/FeedService.java
> +    }
좋은 제안이에요!! 저도 그게 더 흐름이 잘 읽힌다고 생각합니다!!
얼리 리턴 하도록 수정하였습니다 :>

2024-08-04 17:07 UTC, ChaeAg commented on src/main/java/org/websoso/WSSServer/dto/comment/CommentGetResponse.java
> +        String createdDate,
반영했습니다!!

2024-08-04 17:38 UTC, Kim-TaeUk commented on src/main/java/org/websoso/WSSServer/dto/comment/CommentCreateRequest.java
> +        @NotBlank(message = "댓글 내용은 비어 있거나, 공백일 수 없습니다.")
`@NotBlank`가 `null`, `빈문자열("")`, `공백만 포함하는 문자열(ex. " ", "     ")`을 모두 검증하다 보니까
명확하면 좋을 것 같아서 제안했습니닷

2024-08-04 17:40 UTC, Kim-TaeUk commented on src/main/java/org/websoso/WSSServer/domain/Comment.java
> +        if (!Objects.equals(this.userId, userId)) {
어랏 이 말이 이해가 안가는데, 좀 더 자세히 설명해주실 수 있나요??
> 래퍼타입(Long)이여서

2024-08-04 17:42 UTC, Kim-TaeUk commented on src/main/java/org/websoso/WSSServer/dto/comment/CommentGetResponse.java
> +                comment.getCreatedDate().toLocalDate(),
아하 BaseEntity의 createdDate는 LocalDateTime이라서 LocalDate로 바꿔줘야 하는군요 👍

2024-08-04 17:46 UTC, Kim-TaeUk commented on src/main/java/org/websoso/WSSServer/domain/Comment.java
> +    public void validateUserAuthorization(Long userId, Action action) {
오호 기발하네요!

2024-08-05 14:40 UTC, rinarina0429 approved these changes
수고하셨습니다아~

2024-08-06 09:00 UTC, ChaeAg commented on src/main/java/org/websoso/WSSServer/domain/Comment.java
> +        if (!Objects.equals(this.userId, userId)) {
엇 그 처음에 말씀하신대로 비회원인 경우 Long 타입인 userId 에 null 값이 들어갈 수 있기 때문에 Objects.equals() 를 사용한 것입니다!
제가 말을 어렵게 했나봐요 ㅎ.ㅎ

2024-08-06 22:44 UTC, Kim-TaeUk approved these changes
고생하셨습니다~~!

2024-08-07 04:05 UTC, merged