[FEAT] 닉네임, 성별, 출생년도, 취향 등록 기능 구현
Team-WSS/WSS-Server pull request #114
Opened 2024-07-24 21:51 UTC by Kim-TaeUk

## Related Issue

- feat/#24 -> dev
- close #24

## Key Changes

## To Reviewers

2024-07-26 14:25 UTC, Kim-TaeUk commented on src/main/java/org/websoso/WSSServer/domain/User.java
> +})
@Table에서 설정함으로써 unique 제약 조건의 이름 설정 가능

기존 @Column에서 unique = true로 설정해줄 때는 Hibernate가 임의의 이름으로 설정해버림

2024-07-26 14:26 UTC, Kim-TaeUk commented on src/main/java/org/websoso/WSSServer/dto/user/RegisterUserInfoRequest.java
> +        @Range(min = 1900, max = 2024, message = "출생연도는 1900 ~ 2024 사이여야 합니다.")
현재 연도가 2024로 하드 코딩되어 있는데, 어노테이션에서 동적으로 가져오는 방법을 못 찾아서 일단 이렇게 해두었습니다.

2024-07-26 14:31 UTC, Kim-TaeUk commented on src/main/java/org/websoso/WSSServer/exception/handler/GlobalExceptionHandler.java
> +    public ResponseEntity<ErrorResult> MethodArgumentNotValidExceptionHandler(MethodArgumentNotValidException e) {
잡아서 처리하는 예외의 이름으로 handler를 네이밍하고 있어서 rename했습니다.

2024-07-26 14:32 UTC, Kim-TaeUk commented on src/main/java/org/websoso/WSSServer/exception/handler/GlobalExceptionHandler.java
> +
DataIntegrityViolationException이 unique 제약조건을 위반할 때뿐만 아니라, DB의 무결성 제약조건을 위반할 때 터지는 예외인데
nickname(unique 제약조건)이 터질 때를 구분하고 싶어서 따로 분리했습니다.

@Table에서 설정해준 제약조건의 이름인 UNIQUE_NICKNAME_CONSTRAINT을 포함하는지 확인하는 방식입니다.
그렇게 좋은 방식은 아닌 것 같은데, 개선점 말씀해주세요~

2024-07-26 14:34 UTC, Kim-TaeUk commented on src/main/java/org/websoso/WSSServer/validation/NicknameConstraint.java
> +@Target({PARAMETER, FIELD})
기존에는 controller에서 request param에서만 쓰여서 parameter로만 설정해두었는데,
record(dto)에서 쓰이게 돼서 field도 추가했습니다.

2024-07-29 07:13 UTC, ChaeAg approved these changes
수고하셨습니다!
특별히 수정할 것은 없어보입니다!
본문에 남기신 것은 함께 알아보아요 ^^..

2024-07-29 07:13 UTC, ChaeAg commented on src/main/java/org/websoso/WSSServer/service/UserService.java
> +                .collect(Collectors.toList());
P4; 해당 map 구문을 아래와 같이 하는 건 어떨까요? 조금 더 간결해질 수 있을 것 같아 제안합니다!

```java
.map(preferGenreName -> genreRepository.findByGenreName(preferGenreName)
                .map(genre -> GenrePreference.create(user, genre))
                .orElseThrow(() -> new CustomGenreException(GENRE_NOT_FOUND, "genre with the given genreName is not found"))
        )
```

2024-07-29 18:48 UTC, Kim-TaeUk commented on src/main/java/org/websoso/WSSServer/domain/User.java
> +    }
지금 사용한 케이스에서는 딱히 필요한 것 같지는 않지만,
메서드 파라미터의 개수가 많아지는 경우 dto를 파라미터로 넘기는 방식도 있습니다.

메서드 시그니처로 인해 혼란스러울 가능성이 있는 경우에 사용하면 좋을 것 같네요.
ex. 파라미터가 5개인데 모두 String 타입인 경우, 파라미터의 순서를 알려면 해당 메서드가 정의된 곳을 확인해야 하는 번거로움이 있음. (물론 intelliJ에서는 cmd + P하면 나오긴 함 ㅋㅋ,,)

2024-07-29 19:11 UTC, Kim-TaeUk commented on src/main/java/org/websoso/WSSServer/service/UserService.java
> +                .collect(Collectors.toList());
제안된 방식으로 했을 때는 genreName에 해당하는 Genre를 GenreRepository에서 찾을 때 없는 경우 예외를 못 터뜨리지 않나요?

2024-07-30 02:02 UTC, ChaeAg commented on src/main/java/org/websoso/WSSServer/service/UserService.java
> +                .collect(Collectors.toList());
optional의 map 은 값이 없다면 orElse 쪽으로 넘어가는 걸로 아는데.. 아닌가요??

2024-07-31 16:13 UTC, Kim-TaeUk commented on src/main/java/org/websoso/WSSServer/service/UserService.java
> +                .collect(Collectors.toList());
와 그러네요?!?!?!
모르는 부분이었습니다!!! 알려줘서 감사합니다!
반영할게요!

2024-08-01 07:06 UTC, rinarina0429 requested changes
수고하셨습니다~!! 리뷰 한번만 확인 부탁드립니다아

2024-08-01 07:06 UTC, rinarina0429 commented on src/main/java/org/websoso/WSSServer/exception/error/CustomUserError.java
> +    INVALID_PROFILE_STATUS("USER-010", "프로필 상태는 이미 설정된 값과 동일합니다.", BAD_REQUEST),
p3;
```java
ALREADY_SET_NICKNAME("USER-011", "닉네임은 이미 설정된 닉네임과 동일합니다.", BAD_REQUEST);
```
이것처럼 `INVALID_PROFILE_STATUS`보다는 `ALREADY_SET_PROFILE_STATUS`는 어떠신가요? 뭔가 INVALID라고 하면 기존의 의미와 다르게 전달되는 것 같아서요

2024-08-01 07:06 UTC, rinarina0429 commented on src/main/java/org/websoso/WSSServer/service/UserService.java
> +    }
p2;
아래처럼 함수 분리하는건 어떠신가요? 여기서 바로 분리한거라 제대로 된건지는 확인이 필요하겠지만... 지금은 map 안에 map이 있기도 하고 잘 읽히는 느낌이 아니라서요.
그리고 제가 올려둔 pr#120 에도 GenreService 내에 findGenreOrThrow가 있어서 나중에 합치면서 그 함수 하나로 같이 이용할 수 있을 것 같기도 하구요?
```suggestion
public void registerUserInfo(User user, RegisterUserInfoRequest request) {
    validateNickname(request.nickname());
    user.updateUserInfo(request);

    List<GenrePreference> preferGenres = createGenrePreferences(user, request.genrePreferences());
    genrePreferenceRepository.saveAll(preferGenres);
}

private void validateNickname(String nickname) {
    if (userRepository.existsByNickname(nickname)) {
        throw new CustomUserException(DUPLICATED_NICKNAME, "Nickname is duplicated.");
    }
}

private List<GenrePreference> createGenrePreferences(User user, List<String> genreNames) {
    return genreNames.stream()
            .map(this::findGenreOrThrow)
            .map(genre -> GenrePreference.create(user, genre))
            .collect(Collectors.toList());
}

private Genre findGenreOrThrow(String genreName) {
    return genreRepository.findByGenreName(genreName)
            .orElseThrow(() -> new CustomGenreException(GENRE_NOT_FOUND, 
                    genre with the given genreName is not found));
}
```

2024-08-01 08:41 UTC, rinarina0429 commented on src/main/java/org/websoso/WSSServer/dto/user/RegisterUserInfoRequest.java
> +        @Range(min = 1900, max = 2024, message = "출생연도는 1900 ~ 2024 사이여야 합니다.")
`@BirthYearConstraint` 같은거 만들어서 달면 되지 않을까요?
```java
String message() default "출생연도는 {min} ~ {max} 사이여야 합니다.";
```
넣어두고 Validator에서
```java
String messageTemplate = context.getDefaultConstraintMessageTemplate();
String dynamicMessage = messageTemplate
        .replace("{min}", String.valueOf(MIN_YEAR))
        .replace("{max}", String.valueOf(Year.now().getValue()));
```
 요롱식으로??

2024-08-03 03:04 UTC, Kim-TaeUk commented on src/main/java/org/websoso/WSSServer/service/UserService.java
> +    }
와우 반영했습니다
매우 야무져요!!
메서드 참조 쓰니까 훨씬 가독성이 좋아지네요!

2024-08-03 03:11 UTC, Kim-TaeUk commented on src/main/java/org/websoso/WSSServer/exception/error/CustomUserError.java
> +    INVALID_PROFILE_STATUS("USER-010", "프로필 상태는 이미 설정된 값과 동일합니다.", BAD_REQUEST),
그러네요~~!
반영했습니다! 👍

2024-08-03 03:14 UTC, Kim-TaeUk commented on src/main/java/org/websoso/WSSServer/dto/user/RegisterUserInfoRequest.java
> +        @Range(min = 1900, max = 2024, message = "출생연도는 1900 ~ 2024 사이여야 합니다.")
custom으로 만들지 않고 어노테이션에서 동적으로 쓰고 싶어서 그런건데 ㅎㅎ,,,
그냥 custom으로 만들어야겠네요~

2024-08-03 13:17 UTC, rinarina0429 commented on src/main/java/org/websoso/WSSServer/dto/user/RegisterUserInfoRequest.java
> +        @Range(min = 1900, max = 2024, message = "출생연도는 1900 ~ 2024 사이여야 합니다.")
방법이 없다니 허허...ㅜㅜ커스텀을 쓸 수 밖에 없겠네요
근데 메세지에는 2024로 해두고 해가 바뀔 때마다 수정하는 방식인가요?

2024-08-04 08:18 UTC, Kim-TaeUk commented on src/main/java/org/websoso/WSSServer/dto/user/RegisterUserInfoRequest.java
> +        @Range(min = 1900, max = 2024, message = "출생연도는 1900 ~ 2024 사이여야 합니다.")
`유효하지 않은 출생년도입니다.`로 수정했습니다!

2024-08-04 08:50 UTC, rinarina0429 approved these changes

2024-08-04 09:17 UTC, merged