[FEAT] 오늘 인기작 조회 기능 구현
Team-WSS/WSS-Server pull request #115
Opened 2024-07-26 10:41 UTC by Kim-TaeUk

## Related Issue

- feat/#82 -> dev
- close #82

## Key Changes

## To Reviewers

2024-07-26 16:02 UTC, Kim-TaeUk commented on src/main/java/org/websoso/WSSServer/dto/popularNovel/PopularNovelGetResponse.java
> +            );
인기작품에 대응하는 피드글이 없을 때 feed가 null이고, 피드 작성자의 avatarImage 또한 null입니다.
그에 해당하는 response dto입니다.

2024-07-26 16:03 UTC, Kim-TaeUk commented on src/main/java/org/websoso/WSSServer/repository/FeedCustomRepositoryImpl.java
> +    }
novelId로 feed에 조회, like 테이블과 left join하여 feedId로 group by 했습니다.

가장 좋아요를 많이 획득한 feed를 novelId마다 얻어옵니다.

novel에 해당하는 feed가 없는 경우에 NPE 발생하기 때문에 novelId에 해당하는 feed 객체가 null인 경우 filter

2024-07-26 16:05 UTC, Kim-TaeUk commented on src/main/java/org/websoso/WSSServer/repository/UserNovelCustomRepositoryImpl.java
> +                .fetch();
스케쥴링 할 때 사용되는 쿼리입니다.

readstatus가 watching이거나 watched이거나 isInterest가 true이고
최근 7일 동안 등록된 작품 중 가장 인기 있는 작품을 Pageable로 가져옵니다. 

30개씩인데 그보다 적어도 됩니다.

2024-07-26 16:13 UTC, Kim-TaeUk commented on src/main/java/org/websoso/WSSServer/service/NovelService.java
> +        return createPopularNovelsGetResponse(popularNovels, feedMap, avatarMap);
스케쥴링을 통해 갱신해놓은 popularNovel의 Id를 getPopularNovelIds()로 가져오고,
그 중 10개 이하인 경우 모두, 11 ~ 30개인 경우는 랜덤으로 10개를 getSelectedPopularNovelIds()로 가져오고,
그 Id들로 Novel을 가져옵니다. -> popularNovels

그리고 해당 popularNovels에 대응하는 feed도 getPopularFeedsFromPopularNovels()로 가져옵니다. 이 부분은 복잡하여 FeedCustomRepositoryImpl에서 query dsl로 구현했습니다. -> popularFeedsFromPopularNovels

이후 feedMap과 avatarMap으로 만들어서 요구사항에 알맞은 response를 만듭니다!

2024-07-29 07:20 UTC, ChaeAg reviewed
수고하셨습니다!
코멘트 하나만 확인 부탁드려요!

2024-07-29 07:20 UTC, ChaeAg commented on src/main/java/org/websoso/WSSServer/dto/popularNovel/PopularNovelGetResponse.java
> +            );
인기작품에 대응하는 피드글이 없을 때는 작품의 설명이 피드 자리에 들어간다고 피그마에 나와있는데 그 부분은 어디있을까요 ..?

2024-07-29 19:14 UTC, Kim-TaeUk commented on src/main/java/org/websoso/WSSServer/dto/popularNovel/PopularNovelGetResponse.java
> +            );
오 놓친 것 같습니다..!!! 
정말 야무십니다. 수정하고 다시 리뷰 요청하겠습니다!

2024-08-04 08:27 UTC, Kim-TaeUk commented on src/main/java/org/websoso/WSSServer/dto/popularNovel/PopularNovelGetResponse.java
> +            );
> 인기작품에 대응하는 피드글이 없을 때는 작품의 설명이 피드 자리에 들어간다고 피그마에 나와있는데 그 부분은 어디있을까요 ..?

2024-08-04 10:37 UTC, Kim-TaeUk commented on src/main/java/org/websoso/WSSServer/repository/UserNovelCustomRepositoryImpl.java
> +                .fetch();
QUserNovel static import 해서 Outdated 되었네요.

2024-08-04 16:27 UTC, rinarina0429 requested changes
수고하셨습니다!! 리뷰 한번만 확인해주세요~

2024-08-04 16:27 UTC, rinarina0429 commented on src/main/java/org/websoso/WSSServer/service/NovelService.java
> +                    Avatar avatar = avatarMap.get(feed.getUser().getAvatarId());
p3; `avatarRepository.findById(feed.getUser(), getAvatarId());` 로는 안되나요?
avatarMap을 만드신 이유가 궁금함니다!

2024-08-04 16:27 UTC, rinarina0429 commented on src/main/java/org/websoso/WSSServer/service/NovelService.java
> +        List<Feed> popularFeedsFromPopularNovels = getPopularFeedsFromPopularNovels(selectedPopularNovelIds);
p5; 함수명 관련하여 코멘트 남깁니다!
getSelectedPopularNovelIds -> selectPopularNovelIds
getSelectedPopularNovels -> getPopularNovelsByIds
는 어떠신가요?
그리고 getPopularNovelIds에서 저희가 popularNovel이 있다보니 popular한 novel의 novelId가 아니라 popularNovel의 id처럼 느껴지는 것 같습니다. 그치만 이건 어떻게 고치면 좋을지 생각이 안나ㅜㅜ 그냥 떠오르는 다른 좋은 이름이 있다면 rename 하면 좋을 것 같다... 라고 남겨두고 감니다😅

2024-08-04 17:01 UTC, Kim-TaeUk commented on src/main/java/org/websoso/WSSServer/service/NovelService.java
> +                    Avatar avatar = avatarMap.get(feed.getUser().getAvatarId());
> avatarRepository.findById(feed.getUser(), getAvatarId())

stream으로 호출되는 매 라인마다 DB에서 쿼리를 호출하게 될 텐데, 그러면 성능이 매우 안좋아지지 않을까요??

---

> avatarMap을 만드신 이유가 궁금함니다!

DB 호출을 적게 가져가고 싶었고, map 자료구조 사용 시 key 값만 알면 O(1)에 접근할 수 있어서 만들어서 사용하고 있습니다.
avatar의 경우 사용자마다 다 다르지 않고, 비슷한 특정 아바타를 사용중일테니까 DB에서 반복 조회하지 않고 캐싱해서 메모리에 올려두면 성능 상 이점을 가져갈 수 있다고 생각했습니다.

2024-08-04 17:13 UTC, ChaeAg approved these changes
굿! 코멘트 반영된 것 확인했습니다!
수고하셨습니다~!

2024-08-04 17:22 UTC, Kim-TaeUk commented on src/main/java/org/websoso/WSSServer/service/NovelService.java
> +        List<Feed> popularFeedsFromPopularNovels = getPopularFeedsFromPopularNovels(selectedPopularNovelIds);
PopularNovel.popularNovelId가 아닌 PopularNovel.novelId인데 의미가 모호하다는 의미겠죠?

`getNovelIdsFromPopularNovels()`로 rename하면 괜찮겠죠?

2024-08-04 17:33 UTC, Kim-TaeUk commented on src/main/java/org/websoso/WSSServer/service/NovelService.java
> +        List<Feed> popularFeedsFromPopularNovels = getPopularFeedsFromPopularNovels(selectedPopularNovelIds);
https://github.com/Team-WSS/WSS-Server/pull/115/commits/95257a30bc90143c68ece1e764abf37036109406, https://github.com/Team-WSS/WSS-Server/pull/115/commits/98b2e4c6ecc553414a97cda4d1ee69c846e0bdee

반영해보았습니다.

2024-08-05 14:44 UTC, rinarina0429 commented on src/main/java/org/websoso/WSSServer/service/NovelService.java
> +                    Avatar avatar = avatarMap.get(feed.getUser().getAvatarId());
아하 그렇네요 또 배워감니다!

2024-08-05 14:46 UTC, rinarina0429 approved these changes
수고하셨습니다~~!!

2024-08-05 18:02 UTC, merged