[FEAT] 실시간 인기글 조회 기능 구현
Team-WSS/WSS-Server pull request #119
Opened 2024-07-28 17:12 UTC by Kim-TaeUk

## Related Issue

- feat/#116 -> dev
- close #116

## Key Changes

## To Reviewers

2024-07-29 07:25 UTC, ChaeAg approved these changes
수고하셨습니다~~!

2024-07-29 07:25 UTC, ChaeAg commented on src/main/java/org/websoso/WSSServer/service/PopularFeedService.java
> +                ))
P5; 오 혹시 이 DTO는 static 생성 메서드는 구현 안하신 이유가 따로 있으신가용?

2024-07-29 07:25 UTC, ChaeAg commented on src/main/java/org/websoso/WSSServer/repository/PopularFeedCustomRepositoryImpl.java
> +                .fetch();
P5; 우와 대박!

2024-07-29 19:17 UTC, Kim-TaeUk commented on src/main/java/org/websoso/WSSServer/service/PopularFeedService.java
> +                ))
오 딱히 이유는 없었습니다.
요구사항에 맞게 작업해주는게 아니니까 dto에서 하는게 더 낫겠네요! 감사합니다!!

2024-07-29 19:20 UTC, Kim-TaeUk commented on src/main/java/org/websoso/WSSServer/repository/PopularFeedCustomRepositoryImpl.java
> +                .fetch();
JPQL이랑 QueryDSL 둘 다 UNION을 지원하지 않아서 native Query를 쓸까 하다가 
native query가 dbms에 종속적이기도 하고(물론 dbms를 바꿀 것 같진 않긴 하지만,,),
타입 안정성을 챙길 수 없어서 QueryDSL을 선택했습니다.

2024-08-01 13:58 UTC, rinarina0429 requested changes
수고하셨습니다!! 리뷰 한번씩만 확인 부탁드려요~

2024-08-01 13:58 UTC, rinarina0429 commented on src/main/java/org/websoso/WSSServer/controller/FeedController.java
> +    }
p3; 혹시 이런식으로 바꾸는건 어떠실련지요? 분기처리를 해야 하는 다른 로직들(FeedController, UserNovelController 등)에서 위와 같이 쓰고 있어 제안해봅니다!
```suggestion
    @GetMapping("/popular")
    public ResponseEntity<PopularFeedsGetResponse> getPopularFeeds(Principal principal) {
        User user = principal == null ? null : userService.getUserOrException(Long.valueOf(principal.getName()));
        return ResponseEntity
                .status(OK)
                .body(popularFeedService.getPopularFeeds(user));
    }
```

2024-08-01 13:58 UTC, rinarina0429 commented on src/main/java/org/websoso/WSSServer/service/PopularFeedService.java
> +    private static List<PopularFeedGetResponse> getPopularFeedGetResponses(List<PopularFeed> popularFeeds) {
p5; get 말고 convertToPopularFeedGetResponse나 convertToDto와 같은 이름은 어떨까요?

2024-08-01 13:58 UTC, rinarina0429 commented on src/main/java/org/websoso/WSSServer/service/PopularFeedService.java
> +        return getPopularFeedsGetResponse(popularFeedGetResponses);
p5; 요 부분은 그냥 함수 사용하지 않고 그대로 쓰는게 더 잘 읽히지 않을까요?
```suggestion
        return new PopularFeedsGetResponse(popularFeedGetResponses);
```

2024-08-01 13:58 UTC, rinarina0429 commented on src/main/java/org/websoso/WSSServer/repository/PopularFeedCustomRepositoryImpl.java
> +                .toList();
q; 혹시! 이 세 친구들을 하나로 묶을 수는 없을까요? 요롷게는 안되려나요
```suggestion
private List<Long> findBlockedOrBlockingUserIds(Long userId) {
        return jpaQueryFactory
                .select(block.blockingId)
                .from(block)
                .where(block.blockingId.eq(userId)
                        .or(block.blockedId.eq(userId)))
                .fetch();
    }
```

2024-08-01 23:31 UTC, Kim-TaeUk commented on src/main/java/org/websoso/WSSServer/controller/FeedController.java
> +    }
오호 삼항 연산자를 통해 간소화하는 코드네요
반영하겠습니다!

2024-08-01 23:33 UTC, Kim-TaeUk commented on src/main/java/org/websoso/WSSServer/service/PopularFeedService.java
> +        return getPopularFeedsGetResponse(popularFeedGetResponses);
오호 메서드 추출하다가 잘못 들어간 것 같습니다.
반영했습니다!

2024-08-01 23:36 UTC, Kim-TaeUk commented on src/main/java/org/websoso/WSSServer/service/PopularFeedService.java
> +    private static List<PopularFeedGetResponse> getPopularFeedGetResponses(List<PopularFeed> popularFeeds) {
`mapToPopularFeedGetResponseList`로 rename했습니다!

2024-08-01 23:36 UTC, Kim-TaeUk commented on src/main/java/org/websoso/WSSServer/service/PopularFeedService.java
> +    private static List<PopularFeedGetResponse> getPopularFeedGetResponses(List<PopularFeed> popularFeeds) {
get해오는게 아니니까 매우 안좋은 네이밍이었네요! 감사합니다.

2024-08-01 23:40 UTC, Kim-TaeUk commented on src/main/java/org/websoso/WSSServer/service/PopularFeedService.java
> +    private static List<PopularFeedGetResponse> getPopularFeedGetResponses(List<PopularFeed> popularFeeds) {
메서드 네이밍 관련해서 컨벤션으로 정해보면 어떨까 생각들었던게 있어서 공유합니다!

Repository layer에서 생성 - save, 조회 - find
Service layer에서 생성 - create, 조회 - get
으로 사용하시는거 어떤가요??

@rinarina0429 @ChaeAg

2024-08-01 23:49 UTC, Kim-TaeUk commented on src/main/java/org/websoso/WSSServer/repository/PopularFeedCustomRepositoryImpl.java
> +                .toList();
로직이 달라질 것 같은데요~!

2024-08-02 13:27 UTC, rinarina0429 commented on src/main/java/org/websoso/WSSServer/repository/PopularFeedCustomRepositoryImpl.java
> +                .toList();
아니 그렇네요! 왜 저렇게 썼었지 제가 재시도를 해보겠습니다
```suggestion
List<Long> blockIds = jpaQueryFactory
        .select(block.blockingId)
        .from(block)
        .where(block.blockingId.eq(userId)
            .or(block.blockedId.eq(userId)))
        .union(
            jpaQueryFactory
            .select(block.blockedId)
            .from(block)
            .where(block.blockingId.eq(userId)
                .or(block.blockedId.eq(userId)))
        )
        .fetch();
```
이렇게는 어떠신가요? union으로 합치게 되면 distinct로 자동으로 적용되고 별개로 `Stream.concat()`같은 과정도 거칠 필요가 없어질 것 같아서요!

2024-08-02 13:32 UTC, rinarina0429 commented on src/main/java/org/websoso/WSSServer/service/PopularFeedService.java
> +    private static List<PopularFeedGetResponse> getPopularFeedGetResponses(List<PopularFeed> popularFeeds) {
너무 조와요. 앞으로 저렇게 네이밍 하도록 하겟숨댜

2024-08-03 04:07 UTC, Kim-TaeUk commented on src/main/java/org/websoso/WSSServer/repository/PopularFeedCustomRepositoryImpl.java
> +                .toList();
`JPQL`이랑 `QueryDSL`에서는 `UNION`을 지원하지 않아서 공식문서에서 제시해준 방식으로 구현했는데,
혹시 `UNION`을 사용하는 방법이 있는건데 제가 못찾는건가요???....

아래는 References에 작성해둔 공식문서 링크입니다.
> https://github.com/querydsl/querydsl/blob/master/querydsl-sql/src/test/java/com/querydsl/sql/UnionBase.java

2024-08-03 05:13 UTC, Kim-TaeUk commented on src/main/java/org/websoso/WSSServer/repository/PopularFeedCustomRepositoryImpl.java
> +                .toList();
`JPQL`이랑 `QueryDSL`에서는 UNION을 지원하지 않는 것으로 알고 있는데욥, JPAQueryFactory로 .union()을 사용하는 방법 레퍼런스 참고하신 거 있나욥!?

---

query-dsl 공식 github discussions에도 2021년 글이긴 한데 jpa에서는 지원하지 않는다고 나와있고, (https://github.com/querydsl/querydsl/discussions/2927)

query-dsl 공식 github에 jpa가 아닌 native sql로 사용하는 방식은 지원하고 있는 것 같습니다. -> com.querydsl.jpa가 아닌 com.querydsl.sql의 SQLQueryFactory를 사용(https://github.com/querydsl/querydsl/blob/8f96f416270d0353f90a6551547906f3c217833a/querydsl-sql/src/test/java/com/querydsl/sql/UnionBase.java#L73)

---

> JPQL이랑 QueryDSL 둘 다 UNION을 지원하지 않아서 native Query를 쓸까 하다가
native query가 dbms에 종속적이기도 하고(물론 dbms를 바꿀 것 같진 않긴 하지만,,),
타입 안정성을 챙길 수 없어서 QueryDSL을 선택했습니다.

SQLQueryFactory를 사용하고 SQLTemplates로 DBMS에 맞는 SQL 문법을 적용해서 사용할 수 있긴 할 것 같아요!

2024-08-04 09:04 UTC, rinarina0429 commented on src/main/java/org/websoso/WSSServer/repository/PopularFeedCustomRepositoryImpl.java
> +                .toList();
아 그렇네요 그냥 union을 쓰면 편할 것 같다는 생각이었는데

> JPQL이랑 QueryDSL 둘 다 UNION을 지원하지 않아서 native Query를 쓸까 하다가

이걸 읽고 1초만에 까먹은 금붕어가 되었습니다.. 일단은 이대로 사용하는 것도 좋을 것 같네요!

2024-08-04 09:05 UTC, rinarina0429 commented on src/main/java/org/websoso/WSSServer/service/PopularFeedService.java
> +    private static List<PopularFeedGetResponse> getPopularFeedGetResponses(List<PopularFeed> popularFeeds) {
채은언니 확인을 위해 resolve하지 않고 남겨두겠습니다! 머지 전에 resolve 해주세용

2024-08-04 09:06 UTC, rinarina0429 approved these changes
수고하셨습니다~~

2024-08-04 09:27 UTC, merged