[FEAT] 상세 탐색 API 구현
Team-WSS/WSS-Server pull request #120
Opened 2024-07-28 18:48 UTC by rinarina0429

## Related Issue

- feat/#112 -> dev
- close #112 

## Key Changes

상세 탐색 API를 구현하였습니다.

## To Reviewers

## References

2024-07-28 18:49 UTC, rinarina0429 commented on src/main/java/org/websoso/WSSServer/controller/NovelController.java
> +            @RequestParam int page,
인기순으로 정렬이 필요해 lastNovelId가 의미가 없고 + 전체 응답 작품 개수를 함께 응답해야 해서 page를 받는것으로 변경하였습니다.

2024-07-28 18:50 UTC, rinarina0429 commented on src/main/java/org/websoso/WSSServer/domain/Novel.java
> +
작품의 장르를 쭉 가져와야 하는 경우가 있는데, novelGenre 또한 novel 개인에 속하기 때문에 연결해줬습니다.

2024-07-28 18:54 UTC, rinarina0429 commented on src/main/java/org/websoso/WSSServer/repository/NovelRepository.java
쿼리문이 복잡합니다 허허 한번씩 검토해주세요!
일단 제가 만든 모든 경우의 수에는 부합하는데, 오류가 나는 곳 하나...
장르가 작동하지 않습니다ㅜㅜ 원인을 못찾겠어서 도움 청합니댜,,

2024-07-29 07:46 UTC, ChaeAg requested changes
수고많으셨습니다!!!
쿼리가 아주 무지막지한 놈이군여 ...
코멘트 확인 바래요 >< 🤭

2024-07-29 07:46 UTC, ChaeAg commented on src/main/java/org/websoso/WSSServer/repository/NovelRepository.java
> +            "WHERE (ng.genre IN :genres) " +
P3; 이거 ON 으로 바꿔봐주실 수 있으실까여?!

2024-07-29 07:46 UTC, ChaeAg commented on src/main/java/org/websoso/WSSServer/repository/NovelRepository.java
> +            "ORDER BY (SELECT COUNT(un) FROM UserNovel un WHERE un.novel = n AND (un.isInterest = true OR un.status <> 'QUIT')) DESC")
P5; 혹시 이 ORDER BY가 잘 이해가 안돼서 그런데 ㅜㅜ 설명 한 번만 부탁드려도 될까여..
`isInterest = true`를 왜하는 건가요?!

2024-07-29 07:46 UTC, ChaeAg commented on src/main/java/org/websoso/WSSServer/service/NovelService.java
> +        List<UserNovel> userNovels = userNovelRepository.findAllByNovel(novel);
P3; 이거 그냥 `novel.getUserNovels()` 하면 안나오나융??

2024-07-29 07:46 UTC, ChaeAg commented on src/main/java/org/websoso/WSSServer/service/NovelService.java
> +                genres.add(genre);
P3; 이것도 한 줄로 합쳐버리죠! 
`genres.add(genreService.getGenreOrException(genreName));`

2024-07-29 07:46 UTC, ChaeAg commented on src/main/java/org/websoso/WSSServer/service/NovelService.java
> +                keywords.add(keyword);
P3; 이것도 인라인 함수로 합치는 것은 어떠신가유..?! ㅎㅎ......

2024-07-29 16:48 UTC, rinarina0429 commented on src/main/java/org/websoso/WSSServer/repository/NovelRepository.java
> +            "WHERE (ng.genre IN :genres) " +
ON을 사용하면 해당 오류가 납니다..!
<expression>, <operator>, FETCH, GROUP, HAVING, LIMIT, OFFSET or ORDER expected, got 'ON'

2024-07-29 16:51 UTC, rinarina0429 commented on src/main/java/org/websoso/WSSServer/repository/NovelRepository.java
> +            "ORDER BY (SELECT COUNT(un) FROM UserNovel un WHERE un.novel = n AND (un.isInterest = true OR un.status <> 'QUIT')) DESC")
인기순으로 정렬하게 되는데, 이때 인기순이란 "인기는 관심 등록수, 보는 중 등록수, 봤어요 등록수를 총합한 값"입니다. QUIT을 제외하면 되는데, 이때 QUIT이랑 isInterest는 독립이라 isInterest가 true 이거나 status가 QUIT이 아닌 userNovel의 수를 구한겁니다!

2024-07-29 16:55 UTC, rinarina0429 commented on src/main/java/org/websoso/WSSServer/service/NovelService.java
> +        List<UserNovel> userNovels = userNovelRepository.findAllByNovel(novel);
나와요!! 잊고있었네요ㅋㅋㅋㅋㅋ해당 방식대로 수정했습니다!

2024-07-29 16:56 UTC, rinarina0429 commented on src/main/java/org/websoso/WSSServer/service/NovelService.java
> +                genres.add(genre);
좋습니다~~! 수정완입니다

2024-07-29 16:56 UTC, rinarina0429 commented on src/main/java/org/websoso/WSSServer/service/NovelService.java
> +                keywords.add(keyword);
수정완료요~~!

2024-07-29 19:31 UTC, Kim-TaeUk commented on src/main/java/org/websoso/WSSServer/domain/Genre.java
> +public class Genre implements Serializable {
q;
Genre가 Serializable을 구현하게 한 이유가 있나요?

커밋 메시지나 PR에도 이유가 없네요!

2024-07-30 02:07 UTC, ChaeAg commented on src/main/java/org/websoso/WSSServer/repository/NovelRepository.java
> +            "WHERE (ng.genre IN :genres) " +
으악 .. 뭐가 원인일까요 ㅜㅜ

2024-07-30 14:35 UTC, rinarina0429 commented on src/main/java/org/websoso/WSSServer/domain/Genre.java
> +public class Genre implements Serializable {
Servlet.service() for servlet [dispatcherServlet] in context with path [] threw exception [Request processing failed: org.springframework.orm.jpa.JpaSystemException: could not serialize] with root cause

java.io.NotSerializableException: org.websoso.WSSServer.domain.Genre

implements Serializable을 사용하지 않으면 위와 같은 오류가 뜹니다! Genre의 특정 필드가 아니라 Genre 클래스 자체를 읽으려면 직렬화 과정이 필요해 위와 같이 수정하였습니다.

2024-07-31 19:15 UTC, Kim-TaeUk commented on src/main/java/org/websoso/WSSServer/domain/Genre.java
> +public class Genre implements Serializable {
Genre 클래스 자체를 읽어야하는 때가 언제인가요?

2024-08-08 14:40 UTC, Kim-TaeUk approved these changes

2024-08-08 14:56 UTC, ChaeAg approved these changes
새로운 브랜치에서 보아요~~
잠시만 안녕 !!!!

2024-08-08 14:56 UTC, merged