[FIX] 닉네임 유효성 체크 validation 추가
Team-WSS/WSS-Server pull request #123
Opened 2024-07-28 21:45 UTC by Kim-TaeUk

## Related Issue

- fix/#118 -> dev
- close #118

## Key Changes

- 기존 로직에서는 Request header를 안받는 상태였습니다. 누락되어 있었어서 받도록 수정했습니다.
- request의 nickname이 원래의 nickname과 동일한 경우 예외를 던지고 잡아서 처리하도록 수정했습니다.

2024-07-29 07:52 UTC, ChaeAg requested changes
이런 경우도 생각해줘야 하는군요!
수고하셨습니다 ㅎㅎ
코멘트 한 번만 확인 부탁드려용 ☺️

2024-07-29 07:52 UTC, ChaeAg commented on src/main/java/org/websoso/WSSServer/service/UserService.java
> +        }
P3; 유저가 첫 가입했을 때 닉네임 설정 중에 여길 들어왔다면 여기서 혹시 에러가 나지 않을까요??!

2024-07-29 17:06 UTC, Kim-TaeUk commented on src/main/java/org/websoso/WSSServer/service/UserService.java
> +        }
오 NPE 터지겠네요,
아래와 같이 수정했습니다.
`if (user.getNickname() != null && user.getNickname().equals(nickname)) {`

2024-07-30 02:10 UTC, ChaeAg approved these changes
굿입니다!! 🙌 👍

2024-07-30 18:50 UTC, rinarina0429 approved these changes
수고하셨습니다!

2024-07-31 19:17 UTC, merged