[FEAT] 작품정보 조회 API(피드탭) 구현
Team-WSS/WSS-Server pull request #128
Opened 2024-08-01 10:03 UTC by rinarina0429

## Related Issue

- feat/#103 -> dev
- close #103 

## Key Changes

작품정보 조회 API(피드탭)을 구현했습니다.
- 이전 피드 전체 조회에서 쓰인 쿼리문 2개에 괄호를 살짝 수정했습니다.

## To Reviewers

- 피드 전체조회 pr과 크게 다른 점 없어서 금방 확인 하실 수 있을겁니다!

## References

2024-08-02 16:32 UTC, ChaeAg requested changes
수고 많으셨습니다!
메서드명 관련해서 코멘트 남겼어요
제 오류 함께 수정 해주셔서 감사합니다 😊 🙌

2024-08-02 16:32 UTC, ChaeAg commented on src/main/java/org/websoso/WSSServer/service/FeedService.java
> +    public NovelGetResponseFeedTab getNovelInfoFeedTab(User user, Long novelId, Long lastFeedId, int size) {
P3; 혹시 해당 메서드의 이름으로 `getFeedsForNovel` 와 같은 것은 어떠신가용?
피드탭이라는 것은 단순히 클라이언트가 이 API를 호출하는 뷰일 뿐이지 서버 API 와는 관계가 없다고 생각이 들어서요!

2024-08-02 16:32 UTC, ChaeAg commented on src/main/java/org/websoso/WSSServer/controller/NovelController.java
> +    public ResponseEntity<NovelGetResponseFeedTab> getNovelInfoFeedTab(Principal principal,
P3; 해당 메서드 이름도 Tab 이라는 워드를 빼는 것이 어떤지 제안드립니다!

2024-08-03 13:47 UTC, rinarina0429 commented on src/main/java/org/websoso/WSSServer/service/FeedService.java
> +    public NovelGetResponseFeedTab getNovelInfoFeedTab(User user, Long novelId, Long lastFeedId, int size) {
그렇네요!! 나름 통일성을 준다는 것이... 뷰대로 따라가버렸네요? `getFeedsByNovel`로 수정했습니다!!

2024-08-03 13:49 UTC, rinarina0429 commented on src/main/java/org/websoso/WSSServer/controller/NovelController.java
> +    public ResponseEntity<NovelGetResponseFeedTab> getNovelInfoFeedTab(Principal principal,
여기도 getFeedsByNovel로 변경해둔 상태인데, controller에서는 getNovelInfo~로 통일시키는게 나을까요? 만약 그렇다면 Tab없이 getNovelInfoFeed가 더 나아보이시나요??

2024-08-04 10:43 UTC, Kim-TaeUk commented on src/main/java/org/websoso/WSSServer/service/FeedService.java
> +    public NovelGetResponseFeedTab getNovelInfoFeedTab(User user, Long novelId, Long lastFeedId, int size) {
> 피드탭이라는 것은 단순히 클라이언트가 이 API를 호출하는 뷰일 뿐이지 서버 API 와는 관계가 없다고 생각이 들어서요!

오 요즘 이 생각 많이 하는데 뷰는 요구사항에 따라 달라질 수 있으니 네이밍이나 API 설계할 때도 의존성을 가지게 만들면 안되겠더라구요. 
그런 의미에서 노션 `유저 서재 조회 API` 댓글 한 번 확인해주심 감사하겠습니다.

2024-08-04 11:01 UTC, rinarina0429 commented on src/main/java/org/websoso/WSSServer/service/FeedService.java
> +    public NovelGetResponseFeedTab getNovelInfoFeedTab(User user, Long novelId, Long lastFeedId, int size) {
댓글 확인했습니다! 안그래도 작품정보 조회 API 기본과 정보탭에서 저도 비슷한 생각을 했었는데요, 후에 리팩토링 요소로 기록해뒀었는데 서재 조회에서 미리 적용하는거 너무 좋네요👍🏻 해당 pr에 있는 코드들 말고도 rename 등 리팩토링을 한번 하면 좋겠네요! 앞으로 뷰에 의존하지 않은 네이밍과 설계,, 기억해두겠슴다

2024-08-04 17:24 UTC, ChaeAg approved these changes
메서드 네이밍 참 어렵네요 하하 🤨
변경사항 확인했습니다! 수고하셨어요~~!

2024-08-04 17:24 UTC, ChaeAg commented on src/main/java/org/websoso/WSSServer/controller/NovelController.java
> +    public ResponseEntity<NovelGetResponseFeedTab> getNovelInfoFeedTab(Principal principal,
음! 저는 `getFeedsByNovel` 이 더 역할을 잘 나타내고 이름으로 한 눈에 무슨 동작을 하는지 알 수 있는? 메서드명이라고 생각해요
그래서 위의 `getNovelInfoInfoTab` 의 네이밍도 `getNovelInfo` 혹은 `getNovelInfoDetail` 요런식으로 하는 건 어떨까욥?

2024-08-05 17:07 UTC, rinarina0429 commented on src/main/java/org/websoso/WSSServer/controller/NovelController.java
> +    public ResponseEntity<NovelGetResponseFeedTab> getNovelInfoFeedTab(Principal principal,
흠 이부분 메서드명을 일관적으로 getNovelInfoBasic, getNovelInfoInfoTab, getNovelInfoFeedTab과 같이 뷰에 맞춰 네이밍 해둔 상태라 새로운 이슈에서 일관적으로 rename해야할 것 같네요,, 좋은 의견 감사함니다!

2024-08-05 18:34 UTC, Kim-TaeUk commented on src/main/java/org/websoso/WSSServer/service/FeedService.java
> +                user == null ? null : user.getUserId(), PageRequest.of(DEFAULT_PAGE_NUMBER, size));
p3;
`findFeedByNovelId()` 세번째 아규먼트에 삼항 연산자 써서 가독성이 떨어지는 것 같은데 변수로 분리하는거 어떨까요?

2024-08-05 18:34 UTC, Kim-TaeUk commented on src/main/java/org/websoso/WSSServer/service/FeedService.java
> +        List<FeedInfo> feedGetResponses = feeds.getContent().stream().map(feed -> createFeedInfo(feed, user)).toList();
p1;
stream api 컨벤션 적용해주세요~

2024-08-05 18:38 UTC, Kim-TaeUk commented on src/main/java/org/websoso/WSSServer/controller/NovelController.java
> +
p1;
개행 제거 바랍니다~

2024-08-05 18:51 UTC, Kim-TaeUk requested changes
코멘트 남겨두었습니다!

혹싀 rename은 반영안된건가요?

2024-08-06 13:32 UTC, rinarina0429 commented on src/main/java/org/websoso/WSSServer/controller/NovelController.java
> +
제거했습니다~!!

2024-08-06 13:33 UTC, rinarina0429 commented on src/main/java/org/websoso/WSSServer/service/FeedService.java
> +        List<FeedInfo> feedGetResponses = feeds.getContent().stream().map(feed -> createFeedInfo(feed, user)).toList();
적용완입니다~

2024-08-06 13:37 UTC, rinarina0429 commented on src/main/java/org/websoso/WSSServer/service/FeedService.java
> +                user == null ? null : user.getUserId(), PageRequest.of(DEFAULT_PAGE_NUMBER, size));
그렇네요! 적용해줬습니다~

2024-08-07 00:00 UTC, Kim-TaeUk commented on src/main/java/org/websoso/WSSServer/service/FeedService.java
> +        Long userId = user == null
p3;
`userIdOrNull`처럼 의미있는 네이밍은 어떨까요!?

2024-08-07 00:00 UTC, Kim-TaeUk approved these changes

2024-08-07 03:45 UTC, rinarina0429 commented on src/main/java/org/websoso/WSSServer/service/FeedService.java
> +        Long userId = user == null
좋은 것 같습니다! 해당 방식대로 변경했습니다~

2024-08-07 03:52 UTC, merged