[FEAT] 본인 프로필 수정 기능 구현
Team-WSS/WSS-Server pull request #131
Opened 2024-08-05 17:47 UTC by Kim-TaeUk

## Related Issue

- feat/#111 -> dev
- close #111

## Key Changes

- 본인 프로필을 수정하는 API입니다.
- avatarId, nickname, intro, genrePreferences를 프로퍼티로 받는데, 스펙이 PATCH이기 때문에 List 타입인 genrePreferences 제외하고는 null을 허용하도록 했습니다.
  - avatarId, nickname, intro
    - 기존에 설정되어 있는 값과 동일한지 검증합니다.
    - 제네릭을 사용하여 검증 메서드로 분리했습니다. (`checkIfAlreadySetOrThrow()`)
    - nickname을 검증하는 `NicknameConstraint`는 null check를 하기 때문에 `NullAllowedNicknameConstraint`를 정의했습니다. 
    - -> null인 경우(변경하지 않으니 프로퍼티를 보내지 않을 때)는 valid하도록, null이 아닌 경우(변경하기 위해 프로퍼티를 보낼 때)는 `NicknameConstraint`의 validator인 `NicknameValidator`에 validation을 위임합니다.
  - genrePreferences
    - 기존에 설정되어 있는 값과 동일한지 검증하지 않고, 변경하고자 하는 genre들을 모두 받습니다.
    - 기존 값 deleteAll, 변경하고자 하는 값 saveAll로 작동합니다.

2024-08-05 17:51 UTC, Kim-TaeUk commented on src/main/java/org/websoso/WSSServer/domain/User.java
> +    }
Patch라서 변경하지 않고자 하는 값은 request에서 null로 오기 때문에, null이 아닌 유효한 값 즉, 변경하고자 하는 값일 때만 update해주기 위해서 null check를 합니다!

Patch 구현이 좀 애매해서 그런 것 같은데... 나중에 더 공부해서 리팩터링해보려고 합니다.

혹 좋은 방법이 있다면 제안해주세요!

2024-08-05 17:53 UTC, Kim-TaeUk commented on src/main/java/org/websoso/WSSServer/service/UserService.java
> +    private void checkNicknameIfAlreadyExist(String nickname) {
존재하는 nickname인지 확인하는 역할인데 `validateNickname()`라는 메서드명이 모호한 것 같아서
`checkNicknameIfAlreadyExist()`로 rename했습니다.

---

> 메서드명이 모호한 것 같아서

존재 여부 확인 + 이미 세팅된 값과 동일한지 -> 이게 `validateNickname()`이라고 생각했기 때문입니다.

2024-08-05 17:54 UTC, Kim-TaeUk commented on src/main/java/org/websoso/WSSServer/service/UserService.java
> +    }
generic을 사용하여 이미 설정된 값인지 validate하는 메서드를 구현해봤습니다.

2024-08-05 17:55 UTC, Kim-TaeUk commented on src/main/java/org/websoso/WSSServer/validation/NullAllowedNicknameValidator.java
> +    }
null인 경우에는 바로 true를 반환,
null이 아닌 경우에는 NicknameValidator로 위임하는 식으로 구현했습니다.

이전에 `UserIdConstraint`와 `ZeroAllowedUserIdConstraint`와 비슷한 방식입니다.

2024-08-07 14:55 UTC, ChaeAg requested changes
수고하셨어요!
제네릭을 사용하신 것이 신기하네요~
코멘트 남겼습니다! 확인부탁드려요!

2024-08-07 14:55 UTC, ChaeAg commented on src/main/java/org/websoso/WSSServer/service/UserService.java
> +        genrePreferenceRepository.deleteAll(currentPreferGenres);
P3; 해당 작업을 아래와 같은 메서드를 하나 만들어서 `조회->삭제` 를 한번에 수행하는 것은 어떨까요?
```java
genrePreferenceRepository.deleteAllByUser(User user);
```

2024-08-07 14:55 UTC, ChaeAg commented on src/main/java/org/websoso/WSSServer/service/UserService.java
> +        userRepository.save(user);
P2; save 를 해주는 이유가 따로 있을까요? JPA 더티체킹으로 인해서 update는 자동 변경되는 것 아닐까요?!

2024-08-07 17:38 UTC, Kim-TaeUk commented on src/main/java/org/websoso/WSSServer/service/UserService.java
> +        userRepository.save(user);
오호 그러네용
삭제하겠습니닷

2024-08-07 17:43 UTC, Kim-TaeUk commented on src/main/java/org/websoso/WSSServer/service/UserService.java
> +        genrePreferenceRepository.deleteAll(currentPreferGenres);
좋은 생각입니다.
생성과 같은 구조로 만들려다보니 굳이 저렇게 구현했네요.
반영했습니다!

2024-08-08 01:13 UTC, ChaeAg approved these changes
굿입니다~~!!

2024-08-08 14:32 UTC, rinarina0429 requested changes
수고하셨습니다! 리뷰 한번만 확인해주세요~

2024-08-08 14:32 UTC, rinarina0429 commented on src/main/java/org/websoso/WSSServer/exception/error/CustomUserError.java
> +    ALREADY_SET_INTRO("USER-016", "소개글은 이미 설정된 소개글 동일합니다.", BAD_REQUEST);
p2; 단순한 오타인 것 같습니다! 소개글"과" 동일합니다. 로 바꾸면 좋을 것 같습니다!

2024-08-08 14:42 UTC, Kim-TaeUk commented on src/main/java/org/websoso/WSSServer/exception/error/CustomUserError.java
> +    ALREADY_SET_INTRO("USER-016", "소개글은 이미 설정된 소개글 동일합니다.", BAD_REQUEST);
오호 !!! 굿 감사합니다 수정완료!

2024-08-08 14:45 UTC, rinarina0429 approved these changes

2024-08-08 15:06 UTC, merged