[FEAT] 타 유저 프로필 조회 기능 구현
Team-WSS/WSS-Server pull request #133
Opened 2024-08-05 22:09 UTC by Kim-TaeUk

## Related Issue

- feat/#132 -> dev
- close #132

## Key Changes

- 간단한 API입니다.
- 프로필 정보에 해당하는 리소스를 response로 반환합니다.

2024-08-05 22:10 UTC, Kim-TaeUk commented on src/main/java/org/websoso/WSSServer/dto/user/ProfileGetResponse.java
> +) {
유저 프로필 공개 여부가 False인 경우 intro를 보이지 않아야 한다는 정책이 있습니다.
isProfilePublic 프로퍼티를 통해 본인의 프로필인 경우를 처리했습니다.

2024-08-05 22:11 UTC, Kim-TaeUk commented on src/main/java/org/websoso/WSSServer/service/UserService.java
> +
92번째 라인부터 시작되는 `getMyProfileInfo()` 메서드와 많은 부분이 중복되는 로직이 있긴 합니다만, 일단 이렇게 구현했습니다!
리팩터링 할 아이디어가 잘 떠오르지 않네요..ㅜㅜ

2024-08-06 14:12 UTC, rinarina0429 requested changes
수고하셨습니다~ 리뷰 확인 부탁드려요!

2024-08-06 14:12 UTC, rinarina0429 commented on src/main/java/org/websoso/WSSServer/controller/UserController.java
> +                userService.getUserOrException(Long.valueOf(principal.getName()));
p2; [전에 남겨주신 글](https://medium.com/hayanmind-tech-blog-kr/3%ED%95%AD-%EC%97%B0%EC%82%B0%EC%9E%90%EC%9D%98-%EC%9E%AC%EB%B0%9C%EA%B2%AC-a3f815bcdbb8)에서 보이는 것과 다르게 삼항연산자를 개행하셨는데, 이렇게 하신 이유가 있을까요? 전 삼항연산자 개행에서 위 글을 따라서 통일하면 좋을 것 같아서요!
```suggestion
        User user = principal == null
                ? null
                : userService.getUserOrException(Long.valueOf(principal.getName()));
```

2024-08-06 14:12 UTC, rinarina0429 commented on src/main/java/org/websoso/WSSServer/dto/user/ProfileGetResponse.java
> +                                        List<GenrePreference> genrePreferences, boolean isMyProfile) {
p5; 크게 상관은 없어보이지만 isMyProfile을 genrePreferences보다 우선 받는건 어떨까요? 아래서 isMyProfile이 먼저 쓰여서 읽기가 더 좋아질 것 같습니다!

2024-08-06 14:12 UTC, rinarina0429 commented on src/main/java/org/websoso/WSSServer/dto/user/ProfileGetResponse.java
> +                isMyProfile ? true : user.getIsProfilePublic(),
p1; 삼항연산자 개행 부탁드립니다!

2024-08-06 14:12 UTC, rinarina0429 commented on src/main/java/org/websoso/WSSServer/service/UserService.java
> +        return ProfileGetResponse.of(owner, avatar, genrePreferences, false);
p3; 아래와 같이 변경하면 더 쉽게 파악할 수 있을 것 같습니다!
```suggestion
        boolean isOwner = visitor != null && visitor.getUserId().equals(ownerId);
        return ProfileGetResponse.of(owner, avatar, genrePreferences, isOwner);
```

2024-08-06 14:12 UTC, rinarina0429 commented on src/main/java/org/websoso/WSSServer/service/UserService.java
> +                        () -> new CustomAvatarException(AVATAR_NOT_FOUND, "avatar with the given id was not found"));
p3; 요 부분 아래와 같이 함수로 분리해서 getProfileInfo()와 getMyProfileInfo()에서 쓰도록 하면 더 간결할 것 같습니다!
```java
private Avatar getAvatarOrException(Byte avatarId) {
    return avatarRepository.findById(avatarId)
            .orElseThrow(() -> new CustomAvatarException(AVATAR_NOT_FOUND, "avatar with the given id was not found"));
}
```

2024-08-06 22:46 UTC, Kim-TaeUk commented on src/main/java/org/websoso/WSSServer/controller/UserController.java
> +                userService.getUserOrException(Long.valueOf(principal.getName()));
오 개행을 잘못 했네요
저도 아직 익숙치 않은 것 같습니다 ㅋㅋ,, 수정하겠습니다!

2024-08-06 22:47 UTC, Kim-TaeUk commented on src/main/java/org/websoso/WSSServer/controller/UserController.java
> +                userService.getUserOrException(Long.valueOf(principal.getName()));
```suggestion
        User user = 
                principal == null
                ? null
                : userService.getUserOrException(Long.valueOf(principal.getName()));
```

어라 근데 다시 확인해보니까 이렇게 쓰라고 하는데... 어떻게 할까요 ㅋㅋ
제대로 안정해진 것 같아요

2024-08-07 01:43 UTC, Kim-TaeUk commented on src/main/java/org/websoso/WSSServer/dto/user/ProfileGetResponse.java
> +                                        List<GenrePreference> genrePreferences, boolean isMyProfile) {
반영했슴당!

2024-08-07 01:45 UTC, Kim-TaeUk commented on src/main/java/org/websoso/WSSServer/dto/user/ProfileGetResponse.java
> +                                        List<GenrePreference> genrePreferences, boolean isMyProfile) {
반영했슴다!

2024-08-07 01:45 UTC, Kim-TaeUk commented on src/main/java/org/websoso/WSSServer/dto/user/ProfileGetResponse.java
> +                isMyProfile ? true : user.getIsProfilePublic(),
of 메서드 안에서 개행하는 경우 잘 안읽히는 것 같아서, 변수로 분리했습니닷.

2024-08-07 01:49 UTC, Kim-TaeUk commented on src/main/java/org/websoso/WSSServer/service/UserService.java
> +        return ProfileGetResponse.of(owner, avatar, genrePreferences, false);
오호, true/false 직접 넣는 것보다 훨씬 좋겠네요!! 굿 👍

2024-08-07 01:52 UTC, Kim-TaeUk commented on src/main/java/org/websoso/WSSServer/service/UserService.java
> +                        () -> new CustomAvatarException(AVATAR_NOT_FOUND, "avatar with the given id was not found"));
repository에서 찾는거니까 `getAvatarOrException()`보다 `findByIdOrThrow()`로 네이밍했습니닷.

반영 완료~!

2024-08-07 04:41 UTC, rinarina0429 commented on src/main/java/org/websoso/WSSServer/controller/UserController.java
> +                userService.getUserOrException(Long.valueOf(principal.getName()));
저희 정한대로 윗부분처럼 수정하면 될 것 같숨니다!

2024-08-07 15:02 UTC, ChaeAg requested changes
수고하셨습니다!! 😆
코멘트 하나 남겼어용!

2024-08-07 15:02 UTC, ChaeAg commented on src/main/java/org/websoso/WSSServer/service/UserService.java
> +    }
P4; 해당 메서드 이름만 보면 아바타를 조회하는건지 짐작이 안되는 것 같아서, 혹시 네이밍에 아바타를 조회한다는 의미를 담는 것은 어떨까요?
`findAvatarByIdOrThrow()` 처럼이요!

2024-08-07 17:30 UTC, Kim-TaeUk commented on src/main/java/org/websoso/WSSServer/controller/UserController.java
> +                userService.getUserOrException(Long.valueOf(principal.getName()));
반영 완료!

2024-08-07 17:33 UTC, Kim-TaeUk commented on src/main/java/org/websoso/WSSServer/service/UserService.java
> +    }
반영완료!

2024-08-07 23:35 UTC, rinarina0429 approved these changes

2024-08-08 00:34 UTC, Kim-TaeUk commented on src/main/java/org/websoso/WSSServer/service/UserService.java
> +    }
흠 다시 보니 쓰이는 곳을 보면 Avatar라는 타입에 할당해주고 있는데 필요할까 싶네요!

근데 변수에 할당하지 않고 체이닝해서 쓰면 타입을 알기 어려울 것 같아서 쓰는게 좋겠네요! 👍

2024-08-08 01:12 UTC, ChaeAg commented
굿입니다!!

2024-08-08 01:12 UTC, ChaeAg approved these changes

2024-08-08 11:18 UTC, merged