[FEAT] 관심글 조회 기능 구현
Team-WSS/WSS-Server pull request #136
Opened 2024-08-07 16:10 UTC by Kim-TaeUk

## Related Issue

- feat/#135 -> dev
- close #135

## Key Changes

2024-08-07 16:15 UTC, Kim-TaeUk commented on src/main/java/org/websoso/WSSServer/dto/feed/InterestFeedGetResponse.java
> +    }
0.0f가 아닌 경우만 평가함으로 판단

2024-08-07 16:15 UTC, Kim-TaeUk commented on src/main/java/org/websoso/WSSServer/dto/feed/InterestFeedGetResponse.java
> +    }
0.0f가 아닌 경우만 평가함으로 판단

2024-08-07 16:15 UTC, Kim-TaeUk commented on src/main/java/org/websoso/WSSServer/dto/feed/InterestFeedGetResponse.java
> +    }
novelRatingCount가 0일 경우 분모가 0이어서 NaN으로 return됨
-> 0.0으로 return하도록 분기 처리

2024-08-07 16:17 UTC, Kim-TaeUk commented on src/main/java/org/websoso/WSSServer/service/FeedService.java
> +        List<Long> interestNovelIds = new ArrayList<>(novelMap.keySet());
user가 관심으로 등록한 작품을 조회하고, novelId를 key로 하는 map을 만들고, key를 list에 저장합니다.

2024-08-07 16:18 UTC, Kim-TaeUk commented on src/main/java/org/websoso/WSSServer/service/FeedService.java
> +                .collect(Collectors.toMap(Avatar::getAvatarId, avatar -> avatar));
관심으로 등록한 작품에 해당하는 feed를 최신순으로 10개 조회하고, 
feed마다의 user에 해당하는 avatarId를 list에 저장하고,
avatarId를 key로 하는 map을 만듭니다.

2024-08-07 23:47 UTC, rinarina0429 requested changes
수고하셨습니다! 리뷰 한번만 확인 부탁드려요~

2024-08-07 23:47 UTC, rinarina0429 commented on src/main/java/org/websoso/WSSServer/repository/FeedRepository.java
> +    List<Feed> findTop10ByNovelIdIn(List<Long> novelIds);
p1; 요기 LIMIT 10 걸어줘야 하지 않을까요?

2024-08-07 23:47 UTC, rinarina0429 commented on src/main/java/org/websoso/WSSServer/service/FeedService.java
> +        List<InterestFeedGetResponse> interestFeedGetResponseList = interestFeeds.stream()
q; 저희 List<> 는 뒤에 s를 붙이기로 정한 것 같은데 `interestFeedGetResponses`가 아니라 `interestFeedGetResponseList`로 사용하신 이유가 있나요?

2024-08-07 23:49 UTC, Kim-TaeUk commented on src/main/java/org/websoso/WSSServer/repository/FeedRepository.java
> +    List<Feed> findTop10ByNovelIdIn(List<Long> novelIds);
와우 쿼리메서드에만 쓰고 JPQL로는 안적었네요 ㅋㅋ 
수정하겠습니닷

2024-08-07 23:52 UTC, Kim-TaeUk commented on src/main/java/org/websoso/WSSServer/repository/FeedRepository.java
> +    List<Feed> findTop10ByNovelIdIn(List<Long> novelIds);
아 맞다 
JPQL에서 limit 지원 안해서 쿼리메서드로 수정하겠씁니다!

2024-08-07 23:54 UTC, Kim-TaeUk commented on src/main/java/org/websoso/WSSServer/service/FeedService.java
> +        List<InterestFeedGetResponse> interestFeedGetResponseList = interestFeeds.stream()
딱히 이유가 있는 것은 아닌데 생각 없이 쓴 것 같아요
수정하겠습니닷~

2024-08-08 00:09 UTC, rinarina0429 approved these changes

2024-08-08 01:18 UTC, ChaeAg approved these changes
수고하셨어요ㅠㅠ 고생 많으셨습니다!! 굿굿

2024-08-08 01:18 UTC, ChaeAg commented on src/main/java/org/websoso/WSSServer/service/FeedService.java
> +                .toList();
P5; 중복 제거하는 과정을 거쳐야 하니까 Set 으로 받았어도 괜찮았을 것 같네요!

2024-08-08 10:39 UTC, Kim-TaeUk commented on src/main/java/org/websoso/WSSServer/service/FeedService.java
> +                .toList();
반영했습니다
List로 받고 굳이 distinct로 중복 제거하는 것보다 Set을 사용하는 것이 낫겠네요

2024-08-08 15:06 UTC, merged