[FEAT] 취향 추천 작품 조회 기능 구현
Team-WSS/WSS-Server pull request #139
Opened 2024-08-07 23:31 UTC by Kim-TaeUk

## Related Issue

- feat/#134 -> dev
- close #134

## Key Changes

- 유저의 취향 장르에 해당하는 소설 중, 가장 최근에 userNovel로 저장된 10개를 내려주는 API입니다.
- DTO에서 novel에 해당하는 userNovel에 대해 처리하는 로직에 중복이 많습니다. 추후 리팩토링하겠습니다..!

2024-08-07 23:33 UTC, Kim-TaeUk commented on src/main/java/org/websoso/WSSServer/dto/userNovel/TasteNovelGetResponse.java
> +    }
다른 DTO에서도 동일하게 쓰이는 private 메서드입니다. 추후 서비스 레이어에서 공통으로 쓰거나, 
userNovelRating의 제약사항 변경되면 수정될 예정입니다.

2024-08-07 23:37 UTC, Kim-TaeUk commented on src/main/java/org/websoso/WSSServer/repository/UserNovelCustomRepositoryImpl.java
> +    }
유저의 취향 장르에 해당하는 소설 중, 가장 최근에 userNovel로 저장된 10개를 내려주려면
userNovelId로 orderBy해야 해서 Tuple로 프로젝션하여 정렬 후
다시 userNovelId는 제외하고 List<Novel>를 얻어내는 방식을 채택했습니다.

2024-08-08 01:29 UTC, ChaeAg approved these changes
굿 수고하셨습니다!!
코멘트 하나 남겼습니다 :>

2024-08-08 01:29 UTC, ChaeAg commented on src/main/java/org/websoso/WSSServer/service/NovelService.java
> +        List<TasteNovelGetResponse> tasteNovelGetResponseList = tasteNovels.stream()
P1; 여기도 ~List 로 네이밍이 평소랑 다른 것 같네요!!

2024-08-08 10:41 UTC, Kim-TaeUk commented on src/main/java/org/websoso/WSSServer/service/NovelService.java
> +        List<TasteNovelGetResponse> tasteNovelGetResponseList = tasteNovels.stream()
앗 수정했습니닷!

2024-08-08 14:44 UTC, rinarina0429 requested changes
수고하셨습니다~~!

2024-08-08 14:44 UTC, rinarina0429 commented on src/main/java/org/websoso/WSSServer/repository/UserNovelCustomRepositoryImpl.java
> +                        .and(userNovel.createdDate.after(sevenDaysAgo.atStartOfDay())))
p2; 선생님 뭔가 이게 맞는 것 같은데 저도 헷갈려서 한번만 확인 부탁드림니다...
```suggestion
                .where(userNovel.status.eq(ReadStatus.WATCHING)
                        .or(userNovel.status.eq(ReadStatus.WATCHED))
                        .or(userNovel.isInterest.isTrue()))
                        .and(userNovel.createdDate.after(sevenDaysAgo.atStartOfDay()))
```

2024-08-08 14:49 UTC, Kim-TaeUk commented on src/main/java/org/websoso/WSSServer/repository/UserNovelCustomRepositoryImpl.java
> +                        .and(userNovel.createdDate.after(sevenDaysAgo.atStartOfDay())))
무조건입니다 ㅋㅋㅋㅋㅋ 와우 신의 눈

감사하니다

2024-08-08 14:51 UTC, Kim-TaeUk commented on src/main/java/org/websoso/WSSServer/repository/UserNovelCustomRepositoryImpl.java
> +                        .and(userNovel.createdDate.after(sevenDaysAgo.atStartOfDay())))
```java
    .where((userNovel.status.eq(ReadStatus.WATCHING)
        .or(userNovel.status.eq(ReadStatus.WATCHED))
        .or(userNovel.isInterest.isTrue()))
        .and(userNovel.createdDate.after(sevenDaysAgo.atStartOfDay())))
```
where 안에 (), ()이 들어가야 해서 where바로 뒤에 `(` 하나 추가했습니닷

2024-08-08 14:56 UTC, rinarina0429 approved these changes

2024-08-08 15:16 UTC, merged