[FIX] 닉네임 유효성 검사 API 응답 변경
Team-WSS/WSS-Server pull request #148
Opened 2024-08-15 02:28 UTC by Kim-TaeUk

## Related Issue

- feat/#147 -> dev
- close #147

## Key Changes

nickname validation에서 타인 nickname과 중복일 경우 response 변경

## To Reviewers

닉네임 유효성 검사 API에서

1. wooki가 wooki로 유효성 검사하는 경우 -> 400 Bad Request
2. wooki가 이미 존재하는 nickname인 tuna로 유효성 검사하는 경우 -> 409 Conflict
였는데

2. 는 유효성을 검사하는 것일 뿐이지 해당 리소스로 put patch post하는 것이 아니기 때문에 409보다는 200이 좋을 것 같다는 클라의 제안에 수정할 예정입니닷

2024-08-15 05:32 UTC, rinarina0429 requested changes
코멘트 한번만 확인해주세요~

2024-08-15 05:32 UTC, rinarina0429 commented on src/main/java/org/websoso/WSSServer/service/UserService.java
>          checkNicknameIfAlreadyExist(nickname);
p1; 요 부분을 없애야 하지 않을까요?

2024-08-15 06:04 UTC, Kim-TaeUk commented on src/main/java/org/websoso/WSSServer/service/UserService.java
>          checkNicknameIfAlreadyExist(nickname);
오 ㅋㅋㅋㅋㅋㅋㅋㅋ 맞아요....
새로운 로직으로 교체만 하고 기존 로직 삭제를 안했네요 ㅎㅎ,,,
수정하겠습니다

2024-08-15 06:06 UTC, Kim-TaeUk commented on src/main/java/org/websoso/WSSServer/service/UserService.java
>          checkNicknameIfAlreadyExist(nickname);
https://github.com/Team-WSS/WSS-Server/pull/148/commits/c08a5c010460f2bf18e4f55fecbffcc225f420f1

2024-08-15 06:16 UTC, rinarina0429 approved these changes
수고하셨습니다~

2024-08-18 16:03 UTC, ChaeAg approved these changes
그렇군요!
조씁니다
수고하셨어용~~!

2024-08-19 20:03 UTC, merged