[FEAT] 유저 작품 취향 조회 기능 구현
Team-WSS/WSS-Server pull request #149
Opened 2024-08-15 03:25 UTC by Kim-TaeUk

## Related Issue

- feat/#144 -> dev
- close #144

## Key Changes

- 유저가 등록한 userNovel에 해당하는 attractivePoint와 keyword의 취향을 조회하는 api입니다.
- userNovel 리포지토리에서 user에 해당하는 userNovel을 조회하여 가공합니다.
  - attractivePoint의 경우 상위 3개(최대 3개)만 내려줍니다.
  - keyword 많이 선택한 키워드 순으로 내려줍니다.
  - 자세한 로직은 코멘트 추가했습니다.

## To Reviewers

- 많이 선택한 키워드 순으로 내려주기 위해 LinkedHashMap을 사용했습니다.

2024-08-15 03:28 UTC, Kim-TaeUk commented on src/main/java/org/websoso/WSSServer/dto/userNovel/TasteKeywordGetResponse.java
> +    }
Map.Entry를 넘김으로써 key-value로 할당할 수 있었습니다.

2024-08-15 03:28 UTC, Kim-TaeUk commented on src/main/java/org/websoso/WSSServer/service/UserNovelService.java
> +            List<UserNovel> ownerUserNovels = userNovelRepository.findUserNovelByUser(owner);
조회하고자 하는 user의 userNovel을 리포지토리에서 조회하여 얻어온 후

2024-08-15 03:29 UTC, Kim-TaeUk commented on src/main/java/org/websoso/WSSServer/service/UserNovelService.java
> +                    .collect(Collectors.groupingBy(AttractivePoint::getAttractivePointName, Collectors.counting()));
attractivePoint를 attractivePointName을 Key로 개수를 count합니다.
name과 count를 key-value로 가집니다.

2024-08-15 03:29 UTC, Kim-TaeUk commented on src/main/java/org/websoso/WSSServer/service/UserNovelService.java
> +                    .toList();
요구사항에 맞게 상위 3개만, key인 attractivePointName으로 추출합니다.

2024-08-15 03:34 UTC, Kim-TaeUk commented on src/main/java/org/websoso/WSSServer/service/UserNovelService.java
> +                            LinkedHashMap::new));
ownerAttractivePointCountMap와 같은 로직으로 
keyword를 추출, 개수에 따라 map으로 변환합니다.

내림차순 정렬 후 순서 보장을 위해 LinkedHashMap을 사용했습니다.
toMap 메서드의 시그니처를 보면 BinaryOperator<U>타입의 mergeFunction이 있는데, 동일한 키에 대해 여러 개의 값이 존재할 때 이 함수가 호출되어 어떤 값을 유지할지 결정하기 위함입니다. 필수 파라미터라 람다 식으로 표현해주었습니다.
물론 저희 keyword는 중복된 keywordName이 없기 때문에 실제로 중복을 제거하지는 않을 것입니닷.

2024-08-15 08:59 UTC, rinarina0429 requested changes
수고하셨습니다! 리뷰 한번씩 확인해주세요~

2024-08-15 08:59 UTC, rinarina0429 commented on src/main/java/org/websoso/WSSServer/service/UserNovelService.java
> +        if (owner.getIsProfilePublic() || isOwner(visitor, ownerId)) {
p2; 지금처럼 if문 안에 긴 코드를 넣는 것보다 아래와 같이 예외처리를 미리 하고남은 코드를 if문 밖으로 빼는 건 어떨까요?
```java
if (!isProfileAccessible(visitor, owner)) {
    throw new CustomUserException(PRIVATE_PROFILE_STATUS, "the profile status of the user is set to private");
}
```
```java
private boolean isProfileAccessible(User visitor, User owner) {
    return owner.getIsProfilePublic() || isOwner(visitor, owner.getUserId());
}
```

2024-08-15 08:59 UTC, rinarina0429 commented on src/main/java/org/websoso/WSSServer/service/UserNovelService.java
> +                    .toList();
p2; 아래처럼 한번에 구할 수도 있지 않을까요? 단계로 나눈 이유가 있으신가요? 그리고 이렇게 getTop3AttractivePoints()와 같이 메서드를 분리하면 좋을 것 같습니다
```suggestion
private List<String> getTop3AttractivePoints(List<UserNovel> userNovels) {
    return userNovels.stream()
            .map(UserNovel::getUserNovelAttractivePoints)
            .flatMap(List::stream)
            .map(UserNovelAttractivePoint::getAttractivePoint)
            .collect(Collectors.groupingBy(AttractivePoint::getAttractivePointName, Collectors.counting()))
            .entrySet()
            .stream()
            .sorted(Map.Entry.<String, Long>comparingByValue().reversed())
            .limit(3)
            .map(Map.Entry::getKey)
            .collect(Collectors.toList());
}
```

2024-08-15 08:59 UTC, rinarina0429 commented on src/main/java/org/websoso/WSSServer/service/UserNovelService.java
> +                    .toList();
p2; 여기도 함수로 추출하면 좋을 것 같습니다!

2024-08-18 16:16 UTC, ChaeAg reviewed
궁금한 점이 있어 코멘트 하나만 남겨두었습니다!!
ㅎㅎ 수고많으셨어요!!

2024-08-18 16:16 UTC, ChaeAg commented on src/main/java/org/websoso/WSSServer/service/UserNovelService.java
> +                            LinkedHashMap::new));
그런데 궁금한점이 있습니다!
첫번째 collect 부분에서 groupingBy를 통해 키워드 이름을 기준으로 카운트를 해주었는데, 동일한 키에 대해 중복이 발생할 일이 있나용??
가능성이 없다면 해당 mergeFunction은 없어도 되는 것이 아닌가용??

2024-08-19 20:19 UTC, Kim-TaeUk commented on src/main/java/org/websoso/WSSServer/service/UserNovelService.java
> +                            LinkedHashMap::new));
> 필수 파라미터라 람다 식으로 표현해주었습니다.

---
toMap 메서드에서 요구하는 필수 파라미터라서 사용하지 않으면 컴파일 에러가 발생합니닷

2024-08-21 13:44 UTC, Kim-TaeUk commented on src/main/java/org/websoso/WSSServer/service/UserNovelService.java
> +                    .toList();
음 무조건 한 번에 처리하는게 좋다고 생각하지는 않아서요, 논리적 단위에 맞게 구분해서 처리했습니다.
재사용되는 곳이 추가로 있는 곳이 있다면 메서드 추출도 논리적 단위에 맞게 하는게 낫다고 생각하구욥.

메서드 추출도 재사용성이나 유지보수 측면에서 이점이 있기에 사용하면 좋은거지 꼭 해야할 필요가 있을까욥?

---

1. 스트림 같은 체이닝을 한 번에 처리하는 것이 좋은지? 그렇다면 그 이유는 무엇인지?
2. 메서드 추출은 항상 좋은지? 그렇다면 이유는 무엇인지?
에 대한 생각이 궁금하네요~~

2024-08-22 04:41 UTC, rinarina0429 commented on src/main/java/org/websoso/WSSServer/service/UserNovelService.java
> +                    .toList();
1> 한번에 처리하는게 더 간결해보인다고 생각했는데 이건 사람마다 다를 수 있겠네요
2> 매력포인트와 키워드 모두 추출하는 과정이 길어서 해당 상황에서는 메서드를 추출하는게 더 깔끔할 것 같다고 생각했습니다. 근데 이것도 마찬가지로 꼭 필요하지 않다고 생각하신다면..? 굳이긴 하네요
코멘트 확인하시면 resolve 해주세욥!!

2024-08-22 05:40 UTC, ChaeAg commented on src/main/java/org/websoso/WSSServer/service/UserNovelService.java
> +                            LinkedHashMap::new));
앗 그렇군요 ..!!! 허헣허 감사합니다

2024-08-22 05:41 UTC, ChaeAg approved these changes
수고하셨습니당~! 👍

2024-08-22 21:43 UTC, Kim-TaeUk commented on src/main/java/org/websoso/WSSServer/service/UserNovelService.java
> +        if (owner.getIsProfilePublic() || isOwner(visitor, ownerId)) {
괜찮은 생각이네유! 그런데, 조건문의 조건 안에 부정이 아닌 긍정으로 처리하려다 보니 예외처리를 미리할 수는 없었습니다.
(사실 아래에 있으나 위로 올라오나 조건문의 조건에 따라 처리되는거긴 해서!)

어떤게 더 나을까요?

1. 부정 조건으로 사용, 예외 처리 early return
2. 기존 방식대로

2024-08-22 21:43 UTC, Kim-TaeUk commented on src/main/java/org/websoso/WSSServer/service/UserNovelService.java
> +        if (owner.getIsProfilePublic() || isOwner(visitor, ownerId)) {
확인이 늦어서 죄송합니다 ㅎㅎ,,

2024-08-22 21:45 UTC, Kim-TaeUk commented on src/main/java/org/websoso/WSSServer/service/UserNovelService.java
> +                    .toList();
나중에 재사용하게 된다면 메서드로 추출하겠씁니닷!
(재사용을 고려해 이미 생성된 private 메서드들이 잘 사용되지 않는 것 같기도 해서 -> 한 번 전체적인 리팩터링이 필요할 것 같습니닷.)

2024-08-23 04:21 UTC, rinarina0429 commented on src/main/java/org/websoso/WSSServer/service/UserNovelService.java
> +        if (owner.getIsProfilePublic() || isOwner(visitor, ownerId)) {
여기서는 조건을 긍정으로 처리하는 것보다 얼리리턴을 해주는게 더 깔끔할 것 같다는 의견입니다.!만 우기님께서 좋은 것 같은 방식 택해주세요!

2024-08-23 17:02 UTC, Kim-TaeUk commented on src/main/java/org/websoso/WSSServer/service/UserNovelService.java
> +        if (owner.getIsProfilePublic() || isOwner(visitor, ownerId)) {
말씀하신게 더 나은 것 같아서 반영했씁니닷!

2024-08-24 02:42 UTC, rinarina0429 approved these changes

2024-08-26 03:23 UTC, merged