Feat/#145
Team-WSS/WSS-Server pull request #150
Opened 2024-08-19 00:47 UTC by Kim-TaeUk

## Related Issue

- feat/# -> dev
- close #

## Key Changes

## To Reviewers

## References

2024-08-20 19:25 UTC, Kim-TaeUk commented on src/main/java/org/websoso/WSSServer/domain/User.java
> +    }
엔티티의 default 값을 설정해주기 위해 생성자에서 초기화해주었습니다.
`@DynamicInsert`를 사용하려다가 예상하지 못한 곳에서 null처리를 하지 않아도 못 알아차릴 수 있다는 사이드 이펙트때문에 사용하지 않았습니닷.

2024-08-20 19:26 UTC, Kim-TaeUk commented on build.gradle
> +    implementation 'org.springframework.boot:spring-boot-starter-oauth2-client'
Spring Security가 OAuth2 client로 작동하기 위한 의존성을 추가했습니다.

2024-08-20 19:34 UTC, Kim-TaeUk commented on src/main/java/org/websoso/WSSServer/config/SecurityConfig.java
> -        http.authorizeHttpRequests(auth -> {
별건 아닌데 Custom filter chain에서 일부분이 체이닝되어 있지 않아서 체이닝시켰습니다.
결과에 변화는 없습니다.

2024-08-20 19:35 UTC, Kim-TaeUk commented on src/main/java/org/websoso/WSSServer/domain/User.java
> +                columnNames = "social_id")
social_id 컬럼에 대한 unique 제약 조건입니다.

2024-08-20 19:36 UTC, Kim-TaeUk commented on src/main/java/org/websoso/WSSServer/domain/User.java
> +    private String socialId;
socialId라는 새로운 컬럼을 추가했습니다.

2024-08-20 19:36 UTC, Kim-TaeUk commented on src/main/java/org/websoso/WSSServer/domain/User.java
> +    }
아래 createBySocial 메서드에서 사용합니다.

2024-08-20 19:37 UTC, Kim-TaeUk commented on src/main/java/org/websoso/WSSServer/domain/User.java
> +    private String socialId;
`CustomOAuth2UserService` 34line 에서 만들어집니다.
`String socialId = oAuth2Response.getProvider() + "_" + oAuth2Response.getProviderId();`

2024-08-20 19:39 UTC, Kim-TaeUk commented on src/main/java/org/websoso/WSSServer/config/SecurityConfig.java
> +                })
1. `OAuth2 Provider`로부터 인증이 완료된 경우 redirect될 uri를 지정,
2. `OAuth2 Provider`로부터 사용자 정보를 가져오기 위해 `OAuth2UserService`를 사용,
3. OAuth2 인증이 성공적으로 완료된 후 실행될 커스텀 성공 핸들러 설정

2024-08-20 19:40 UTC, Kim-TaeUk commented on src/main/java/org/websoso/WSSServer/oauth2/CustomAuthenticationSuccessHandler.java
OAuth2 인증이 성공적으로 완료된 후 실행될 custom success handler

2024-08-20 20:04 UTC, Kim-TaeUk commented on src/main/java/org/websoso/WSSServer/oauth2/CustomAuthenticationSuccessHandler.java
> +        CustomOauth2User customOauth2UserDetails = (CustomOauth2User) authentication.getPrincipal();
SecurityContext에서 유저 인증 정보 가져옴

2024-08-20 20:04 UTC, Kim-TaeUk commented on src/main/java/org/websoso/WSSServer/oauth2/CustomAuthenticationSuccessHandler.java
> +        response.getWriter().write("{\"authorization\": \"" + token + "\"}");
HttpServletResponse로 jwt를 http Response로 내려줌

2024-08-24 05:05 UTC, rinarina0429 requested changes
소셜로그인이 드디어~~ 수고하셨습니다. 코멘트 한번만 확인해주세요!!

2024-08-24 05:05 UTC, rinarina0429 commented on src/main/java/org/websoso/WSSServer/domain/User.java
> +        this.role = Role.USER;
p4; 요기 static import 해주면 좋을 것 같습니다!

2024-08-24 05:05 UTC, rinarina0429 commented on src/main/java/org/websoso/WSSServer/oauth2/dto/CustomOauth2User.java
> +public class CustomOauth2User implements OAuth2User {
p3; OAuth2User에 맞게 해당 class 이름도 CustomOAuth2User로 rename하는건 어떠신가요?

2024-08-24 05:05 UTC, rinarina0429 commented on src/main/java/org/websoso/WSSServer/oauth2/dto/KakaoOauth2Response.java
> +public class KakaoOauth2Response implements OAuth2Response {
p3; 여기도 rename하면 좋을 것 같슴다!

2024-08-24 14:54 UTC, ChaeAg requested changes
매우 수고하셨습니다!
유저 닉네임 저장 관련 에러만 해결하면 될 것 같습니다! 👍 👍

2024-09-02 08:24 UTC, Kim-TaeUk commented on src/main/java/org/websoso/WSSServer/domain/User.java
> +        this.role = Role.USER;
반영했습니닷!

2024-09-02 08:24 UTC, Kim-TaeUk commented on src/main/java/org/websoso/WSSServer/oauth2/dto/CustomOauth2User.java
> +public class CustomOauth2User implements OAuth2User {
반영했습니닷!

2024-09-02 08:25 UTC, Kim-TaeUk commented on src/main/java/org/websoso/WSSServer/oauth2/dto/KakaoOauth2Response.java
> +public class KakaoOauth2Response implements OAuth2Response {
반영했습니닷!

2024-09-02 10:57 UTC, ChaeAg approved these changes
수고 많으셨습니다!! 👍

2024-09-02 11:30 UTC, rinarina0429 approved these changes
수고하셨습니다~~

2024-09-02 14:11 UTC, merged