[FIX] 엔티티 재설계
Team-WSS/WSS-Server pull request #93
Opened 2024-07-09 11:20 UTC by ChaeAg

## Related Issue

- fix/#92 -> dev
- close #92

## Key Changes

### 엔티티 재설계를 진행하였습니다.

> 수정 후 ERD  :  https://www.erdcloud.com/d/f9XQq6ipHW5rey9SR
일단 제 ErdCloud에 만들어놨고 이대로 픽스한다면 팀 ERD에 반영하죠!

크게, 바뀐 것은 아래와 같습니다.
- 통계성 테이블이 제거됨.
- 반정규화 컬럼이 제거됨.
- 새로운 관계들이 형성됨.

엔티티 재설계로 인해 바뀔 로직은 수정하지 않은 상태이기 때문에, 
각자 브랜치를 하나씩 파서 자신이 개발했던 로직을 수정하는 것이 어떨까 합니다.

궁금한 것은 질문 정말 환영이고, 잘못된 것 찾아주시면 정말 감사하겠습니다!! 🥹 🙌

## To Reviewers

## References

2024-07-09 15:57 UTC, rinarina0429 requested changes
건드릴게 정말 많았네요 너무너무 수고하셨습니다

2024-07-09 15:57 UTC, rinarina0429 commented on src/main/java/org/websoso/WSSServer/domain/Genre.java
> +    @Column(columnDefinition = "varchar(5)", nullable = false)
p1; 저희 이거 최대 글자수 4 아닌가요?
라이트노벨을 라노벨로 하기로 해서 5글자가 없어졌던 것 같슴다!

2024-07-09 15:57 UTC, rinarina0429 commented on src/main/java/org/websoso/WSSServer/domain/common/Flag.java
Flag도 사라졌네요!!👍🏻👍🏻👍🏻

2024-07-10 06:55 UTC, ChaeAg commented on src/main/java/org/websoso/WSSServer/domain/Genre.java
> +    @Column(columnDefinition = "varchar(5)", nullable = false)
헉 ! 그렇네요! 수정했습니다!

2024-07-10 06:56 UTC, ChaeAg commented on src/main/java/org/websoso/WSSServer/domain/common/Flag.java
하핳 맞습니다.. 이왕 다 고칠거 없애버려써요!!

2024-07-10 10:00 UTC, Kim-TaeUk commented on src/main/java/org/websoso/WSSServer/domain/AttractivePoint.java
> +    @OneToMany(mappedBy = "attractive_point", cascade = ALL, fetch = FetchType.LAZY)
p4;
`@XXToMany`는 default가 LAZY인데, 명시해준 이유가 있나요?

2024-07-10 10:14 UTC, Kim-TaeUk commented on src/main/java/org/websoso/WSSServer/domain/Avatar.java
> +    @OneToMany(mappedBy = "avatar", cascade = ALL, fetch = FetchType.LAZY)
p2;
AvatarLine이 avatar의 개인 소유라서 cascade걸어 준 것은 좋은데,
orphanRemoval 설정도 같이 해주면 좋을 것 같습니다.

2024-07-10 10:20 UTC, Kim-TaeUk commented on src/main/java/org/websoso/WSSServer/domain/ReportedComment.java
> +    private Comment comment;
ReportedComment는 Comment를 참조해야 하니까 양방향 매핑 잘 되어 있는 것 같습니다! 👍

2024-07-10 10:24 UTC, Kim-TaeUk commented on src/main/java/org/websoso/WSSServer/domain/common/CategoryName.java
>      private final String value;
p3;
변경 사항은 없지만 확인하다가 코멘트 남깁니다.
KeywordCategoryName에서는 필드명을 name으로 사용하고 있더라구요, value보다 name이 더 적절할 것 같은데 어떻게 생각하시나요? value나 name이 아니더라도 KeywordCategoryName랑 CategoryName에서 같은 필드명을 사용하는게 더 나을 것 같습니다.

2024-07-10 10:25 UTC, Kim-TaeUk commented on src/main/java/org/websoso/WSSServer/domain/common/KeywordCategoryName.java
> +public enum KeywordCategoryName {
p4;
열거형의 이름이 바뀐 이유가 있나요?

2024-07-10 10:30 UTC, Kim-TaeUk commented on src/main/java/org/websoso/WSSServer/domain/Comment.java
> +    @OneToOne(mappedBy = "comment", cascade = ALL, fetch = FetchType.LAZY)
p2;
comment가 삭제되어도 reportedComment가 삭제되면 안될 것 같은데, cascade가 들어가있는 것 같아요.

2024-07-10 10:35 UTC, Kim-TaeUk commented on src/main/java/org/websoso/WSSServer/domain/Comment.java
> +    @OneToOne(mappedBy = "comment", cascade = ALL, fetch = FetchType.LAZY)
흠 근데 이건 cascade랑 별개로, ReportedComment가 comment_id로 어떤 내용인지 알 수 있어야 할 것 같은데
Comment가 삭제되면 확인할 수 없는 문제가 있을 것 같은데,, -> 제가 잘못 생각하고 있는건가유?!

제 생각이 맞다면 soft delete를 해야 할 것 같은데요!? 어떻게 생각하시나유?

2024-07-10 10:35 UTC, Kim-TaeUk commented on src/main/java/org/websoso/WSSServer/domain/Comment.java
> +    @OneToOne(mappedBy = "comment", cascade = ALL, fetch = FetchType.LAZY)
> 흠 근데 이건 cascade랑 별개로, ReportedComment가 comment_id로 어떤 내용인지 알 수 있어야 할 것 같은데 Comment가 삭제되면 확인할 수 없는 문제가 있을 것 같은데,, -> 제가 잘못 생각하고 있는건가유?!
> 
> 제 생각이 맞다면 soft delete를 해야 할 것 같은데요!? 어떻게 생각하시나유?

아 Feed에서도 같은 상황이겠네요

2024-07-10 12:13 UTC, ChaeAg commented on src/main/java/org/websoso/WSSServer/domain/AttractivePoint.java
> +    @OneToMany(mappedBy = "attractive_point", cascade = ALL, fetch = FetchType.LAZY)
엇 따로 이유가 있는 것은 아니고, default 값을 고려하지 않고 그냥 모두 작성해주었어요!
기본값이 LAZY 로딩인 것들은 지우는 것이 나을까요?

2024-07-10 12:14 UTC, ChaeAg commented on src/main/java/org/websoso/WSSServer/domain/common/KeywordCategoryName.java
> +public enum KeywordCategoryName {
Keyword의 카테고리 정보를 담는 KeywordCategory 테이블이 새로 생기면서 해당 이름이 중복되어 새롭게 변경했습니다!

2024-07-10 12:16 UTC, ChaeAg commented on src/main/java/org/websoso/WSSServer/domain/Comment.java
> +    @OneToOne(mappedBy = "comment", cascade = ALL, fetch = FetchType.LAZY)
엇 제가 생각했을 땐 reportedComment는 신고 받은 댓글이 담기는 곳인데, 신고된 댓글이 삭제된다면 해당 댓글의 신고 기록은 없애도 되지 않나용??

2024-07-10 12:21 UTC, ChaeAg commented on src/main/java/org/websoso/WSSServer/domain/common/CategoryName.java
>      private final String value;
음 저도 이 부분에 대해 잠깐 고민을 했었는데요
같은 필드명을 사용하면 좋을 것 같은 것은 저도 동의합니다!
그런데, name을 안쓴 이유는.. enum 클래스에 `name()` 이라는 메서드가 따로 존재해서 조금 헷갈릴 요소가 있는 것 같아 value로 지정을 했습니다..!
name, value 가 다 조금 그렇다면 label 은 어떨까요?

2024-07-10 12:45 UTC, ChaeAg commented on src/main/java/org/websoso/WSSServer/domain/Avatar.java
> +    @OneToMany(mappedBy = "avatar", cascade = ALL, fetch = FetchType.LAZY)
지당하신 말씀입니다!
Avatar AvatarLine 뿐 아니라 개인 소유인 관계가 여럿 되어, 모두 orphanRemoval 설정 추가해두었습니다!

2024-07-10 13:41 UTC, rinarina0429 commented on src/main/java/org/websoso/WSSServer/domain/common/CategoryName.java
>      private final String value;
모두 name이라고 하고 enum에서의 메서드를 `value()`라고 바꾸는건 어떤가요?

2024-07-11 06:07 UTC, Kim-TaeUk commented on src/main/java/org/websoso/WSSServer/domain/common/CategoryName.java
>      private final String value;
> enum 클래스에 `name()` 이라는 메서드가 따로 존재해서 

@rinarina0429  여기서 말한 name()은 Java Enum에 정의된 메서드를 말하는거 아닌가요??

2024-07-11 06:08 UTC, Kim-TaeUk commented on src/main/java/org/websoso/WSSServer/domain/common/CategoryName.java
>      private final String value;
> name, value 가 다 조금 그렇다면 label 은 어떨까요?

Enum 자체에서 name() 메서드를 제공하니까
필드명을 name으로 설정하기보다 제안하신대로 label이 적절한 것 같습니다!

2024-07-11 06:10 UTC, Kim-TaeUk commented on src/main/java/org/websoso/WSSServer/domain/Comment.java
> +    @OneToOne(mappedBy = "comment", cascade = ALL, fetch = FetchType.LAZY)
신고 기록만 저장하는 역할이니까 계속 유지되어야 한다고 생각했는데,
신고된 댓글을 DB에 가지고 있을 필요가 없을까요?

2024-07-11 06:10 UTC, Kim-TaeUk commented on src/main/java/org/websoso/WSSServer/domain/common/KeywordCategoryName.java
> +public enum KeywordCategoryName {
아하 그러네요! 확인했습니다

2024-07-11 06:27 UTC, Kim-TaeUk commented on src/main/java/org/websoso/WSSServer/domain/AttractivePoint.java
> +    @OneToMany(mappedBy = "attractive_point", cascade = ALL, fetch = FetchType.LAZY)
움 default인걸 쓰는게 굳이라고 생각하긴 했습니다.
생소해서 모르는거에 default를 명시해주는거면 좋을 거 같은데, 00ToMany는 그렇진 않은 것 같아서요!

근데 또 굳이 지우진 않아도 될 것 같습니다 ^^
(코멘트는 특별한 이유가 있나 해서 물어봤습니다)

2024-07-11 08:26 UTC, ChaeAg commented on src/main/java/org/websoso/WSSServer/domain/common/CategoryName.java
>      private final String value;
> @rinarina0429 여기서 말한 name()은 Java Enum에 정의된 메서드를 말하는거 아닌가요??

맞습니다! Enum 클래스에서 기본적으로 제공하는 `name()` 메서드가 존재하고 `RO`, `ETC` 와 같은 상수 이름을 return 하는 메서드입니당!
저희가 name 필드를 만들어서 @getter 어노테이션을 통해 사용하는 것은 `getName()` 이 됩니다!
이게 조금 헷갈리는 요소가 될 것 같애서 말씀드렸어용ㅎ.ㅎ
그렇다면 label로 가보도록 할게요!

2024-07-11 08:31 UTC, ChaeAg commented on src/main/java/org/websoso/WSSServer/domain/Comment.java
> +    @OneToOne(mappedBy = "comment", cascade = ALL, fetch = FetchType.LAZY)
저는 없을 것 같다고 생각이 듭니다
삭제된 댓글에 대한 신고기록을 계속 저장해두어도 
신고와 연결된 댓글 ID에 대한 정보만 남고, ID를 통해 이미 삭제된 댓글에 대한 어떠한 정보도 알 수 없으니까..?

2024-07-11 09:45 UTC, rinarina0429 commented on src/main/java/org/websoso/WSSServer/domain/common/CategoryName.java
>      private final String value;
getName()이랑 헷갈렸네요ㅎㅎ label 좋슴니당~~

2024-07-11 10:00 UTC, Kim-TaeUk commented on src/main/java/org/websoso/WSSServer/domain/Comment.java
> +    @OneToOne(mappedBy = "comment", cascade = ALL, fetch = FetchType.LAZY)
오호 그게 맞네욥
그럼 신고가 발생하면 이벤트처리가 필요하겠네여!

2024-07-11 10:00 UTC, Kim-TaeUk approved these changes

2024-07-11 10:03 UTC, rinarina0429 approved these changes

2024-07-11 10:04 UTC, merged